### ISSUE TITLE
Feature Request: Please add litd as an option for custom containers

### ISSUE THREAD

**Issue by ZZiigguurraatt** [jamaljsr/polar#1052]
Please add litd as an option for custom containers so that it shows up here:

![image](https://github.com/user-attachments/assets/1a2da96a-089a-4f65-8ad9-eafb1bf0cf18)

because it would be nice to be able to test more bleeding edge versions of litd.

I think this feature might be blocked by 

https://github.com/jamaljsr/polar/pull/1039

and

https://github.com/jamaljsr/polar/pull/1040

not sure.

**Comment by jamaljsr** [comment]
Thanks for the report. I've added a commit to #1040 to fix this. It'll be resolved when that PR is merged.

**Comment by jamaljsr** [comment]
#1040 depends on #1039 which depends on the `litd` PR https://github.com/lightninglabs/lightning-terminal/pull/848 being merged and shipped in a new release.
