### ISSUE TITLE
Displays "undefined sats" for 0

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#195]
**Describe the bug**

The channel info display shows "undefined sats" seemingly when it should be zero.

**To Reproduce**
1. Open a fresh one sided channel
2. Inspect it & observe

**Screenshots**

<img width="341" alt="Screen Shot 2019-10-20 at 9 48 58 AM" src="https://user-images.githubusercontent.com/649992/67167356-26eb2000-f399-11e9-8167-c8a99167e87a.png">

**Comment by jamaljsr** [comment]
Ughh! so much for unit tests. lol

Thanks for catching this. Looks like I broken it in my last PR. I’ll get it fixed.
