### ISSUE TITLE
Feature request: Allow export and import of networks

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#203]
It would be awesome if we could easily export network state the build up, and send it to other people to import or just use it to restore from if you have a specific state you want to use (testing, tutorials, bug reports etc.)

Docker seems to [support this out of the box](https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes), so hopefully it would just be a matter of packing and unpacking volumes.

**Comment by jamaljsr** [comment]
Cool idea. I like it!

I want to add pre-defined and user-defined network templates. So you can quickly spin up a network of mixed nodes (when other implementations are supported) with them funded and/or channels opened. I hadn't thought of the backup/restore/share state scenario which is somewhat related, but slightly more powerful. This will be fun to implement.

Thanks for the feedback
