### ISSUE TITLE
Allow inspection of errors

### ISSUE THREAD

**Issue by wbobeirne** [jamaljsr/polar#221]
**Describe the bug**
I've had a couple of cases of my LND nodes not starting. It lets me know there's an error, but I have no way of investigating why that may be. This may also be really useful for debugging issues that are sure to crop up on various user's systems. 

**To Reproduce**
Hard to reproduce, but cause an LND node to not launch properly.

**Expected behavior**
Some kind of error message that would tell me what went wrong.

**Screenshots**

<img width="1172" alt="Screen Shot 2019-10-25 at 4 57 57 PM" src="https://user-images.githubusercontent.com/649992/67604143-d254f580-f748-11e9-9295-2129bafb5251.png">

**Comment by jamaljsr** [comment]
I've ran into that myself. Been meaning to display the error in the UI. Thanks for submitting the issue so i won't forget.

Were you able to get the nodes started?

FYI: there's a log file which will likely have the error in it. On OSX the file is located at `/Users/<username>/Library/Logs/polar/log.log`

**Comment by wbobeirne** [comment]
Ended up blowing away the network and starting a new one up. I'll try to save any networks I break going forward though!
