### ISSUE TITLE
Error when opening channels

### ISSUE THREAD

**Issue by apotdevin** [jamaljsr/polar#248]
Hey just downloaded version 0.4.0, started a new network, and when I went to create a new channel this error appeared. I can see the channel is opened through the cli but the UI doesn't update and keeps showing this error

![image](https://user-images.githubusercontent.com/31413433/69373900-2ea62900-0ca5-11ea-9095-48607d79f31c.png)

**Comment by jamaljsr** [comment]
Hey @apotdevin that's an error I haven't seen before. I skimmed through that code path and do not see anything obvious that could cause this error. Are you able to reproduce the error or was it a one-time issue?

**Comment by apotdevin** [comment]
Can reproduce every time I create a new network. Let me try deleting everything and starting fresh

**Comment by apotdevin** [comment]
Yep, deleting everything seems to have solved it. Will let you know if it comes again 👍

**Comment by jamaljsr** [comment]
Interesting. I'm curious what the problem was, but since you got it resolved 'm going to close out this issue for now.
