### ISSUE TITLE
Feature request: Start nodes with local docker images

### ISSUE THREAD

**Issue by arvchristos** [jamaljsr/polar#255]
Hello!
I think it would be great for developers to be able to define which image will be used for a node, apart from the predefined ones you already use. This way, we could even test modifications in the lnd itself (I am trying to use a forked lnd version and face difficulties changing the docker image used)
Thank you for the useful project!

**Comment by jamaljsr** [comment]
Hey @arvchristos this is a pretty good idea. It wouldn’t be difficult at all to add the ability to use custom images for each node. The app can even automatically detect docker images that you’ve built locally to display in a list to choose from.

Thanks for the suggestion.

**Comment by jamaljsr** [comment]
@arvchristos I've been thinking about how to implement this feature and I see a few approaches I could take. 

Specify the docker image...
1. one time for the whole app per node implementation. For example, change all LND nodes from using `polarlightning/lnd:0.8.2-beta` to use `mycustomimage:latest`. This approach allows you to only configure it one time, then you can create many networks and all LND nodes will use this image. The down side is you have to remember to change it before creating the network.
2. at the Network level. With this approach, you can set all LND nodes in the new Network to use `mycustomimage:latest`. The up side is that it's easier than option 1 to use your custom image. The downside is that you cannot mix & match in a single network.
3. at the Node level. I imagine you creating a network, then before starting it, you click on each node you wish to change and configure an option to specify the `mycustomimage:latest`. The upside is you get maximum flexibility. The downside is that this approach requires the most amount of clicks when creating the network.

I'd like to get your input to make sure this feature satisfies what you'd like to accomplish without being a huge burden. I personally am leaning towards option 3, but I have never needed this functionality myself, so my opinion is a little less relevant. Please let me know your thoughts.

**Comment by arvchristos** [comment]
@jamaljsr I think that option 3 is the most useful, not only for me but for most developers. Imagine having to test how a custom image interacts with previous versions in a network. 
Thank you for taking the time to implement my feature request !!!

**Comment by tiero** [comment]
+1 I really like to use Polar for testing latest master of lnd (eg. trying the keysend feature)

Any ETA on this?

**Comment by jamaljsr** [comment]
@tiero I've spent the past 2 weeks testing and fixing bugs on Linux and Windows. I plan to release a new version next week with support for the latest releases of LND, c-lightning & bitcoind.

**Comment by torkelrogstad** [comment]
It would be really nice if it was possible to specify Docker images that's not on Docker hub. I.e. either images built off of a local `Dockerfile`, or an image sitting on a authenticated registry.

**Comment by jamaljsr** [comment]
@torkelrogstad My plan was to allow you to specify the name of the docker image. This would just be used in the `image` field of the `docker-compose.yml` file. It would be up to you to ensure that docker can find this image locally or remotely when Polar runs `docker-compose up`.
