### ISSUE TITLE
Cannot push new lnd to docker hub repo

### ISSUE THREAD

**Issue by johncantrell97** [jamaljsr/polar#283]
In the docker/README.md it says we can build our own versions of lnd/bitcoind/clightning and then push those builds to docker hub to update them out-of-band with updates to polar.

1. cd docker/lnd
2. docker build --build-arg LND_VERSION=0.9.0-beta -t polarlightning/lnd:0.9.0-beta .
3. docker push polarlightning/lnd:0.9.0-beta

Receive error:

denied: requested access to the resource is denied.

It makes sense to me that your dockerhub repos would be private but then I'd expect to be able to update Polar to point to a different dockerhub repo? Which I guess I could edit nodeTemplate.ts to point to a different repo but the instructions make it seem like I shouldn't have to do that?

Am I missing something?

**Comment by jamaljsr** [comment]
You are correct. The instructions in the docker readme is really just documentation for my future as well as any maintainers of the project that I would give write access to the repo. It would be pretty bad to allow anyone to update those images that everyone uses. 

There is already issue #255 which I am working on which will allow Polar to use any local docker image on your machine for the nodes. This way, you will be able to use whichever versions of the nodes that you like, or even your own custom builds.

Regarding the new LND v0.9.0 release, I am going to create the images and test on all OS’s. If there are no compatibility issues, then I will push the new images to DockerHub later on today. If there are any issues that require an update to Polar, then it may take me a bit longer to fix, test, and package a new release.

**Comment by johncantrell97** [comment]
Got it, that was my best guess (that it was mostly a note for yourself to remember).  Cool, looking forward to the 0.9.0 lnd release and hope there's no major issues.
