### ISSUE TITLE
Console error when starting a network

### ISSUE THREAD

**Issue by bolatovumar** [jamaljsr/polar#284]
See the screenshot below for the error I see in the console when starting a new network:

![Screen Shot 2020-01-23 at 8 10 11 PM](https://user-images.githubusercontent.com/1934678/73044024-acf58780-3e1c-11ea-956b-10d57a99a108.png)

As you can see from the log the `data` parameter in `log()` method doesn't have a `body` in request (see the log of the request in the top section of the screenshot).

Not sure if this error matters at all but thought I would bring it up.

**Comment by jamaljsr** [comment]
Oops, that does look like a bug. It should check that the `body` is defined or wrap that statement in a try/catch.
