### ISSUE TITLE
Feature Request: connect to nodes outside of Polar

### ISSUE THREAD

**Issue by torkelrogstad** [jamaljsr/polar#288]
I'm developing an app where I have a pre-existing LND setup. It'd be great if I could connect this to Polar. I'm running my dev environment with `docker-compose`, with an instance of LND connected to `bitcoind`. Through some hacking around with the `$HOME/.polar/networks/1/docker-compose.yml` file I managed to connect my nodes and send payments, although nothing showed up in the GUI (as expected). 

What I did: 

1. Edited the `$HOME/.polar/networks/1/docker-compose.yml` file, by adding
    ```
    networks:
      default:
        external:
          name: my-network
    ```
    at the bottom
2. Doing `docker-compose up -d` in the `$HOME/.polar/networks/1` directory

I was then able to use the terminals in Polar to issue commands to connect with my other nodes. Would something like this make sense to add to Polar? You could have a box (under advanced settings, or something like that) where a custom `docker-compose` network could be specified, and also some connection settings for where to find the new nodes. These could then show up in the explorer as "external nodes" where what information we could retrieve can be displayed, but it would not be possible to issue commands to these nodes directly.

**Comment by jamaljsr** [comment]
Hey @torkelrogstad can you provide a bit more information about your use case. I don't quite understand why you would use your own node instead of the nodes included in Polar. How are your nodes different?

**Comment by torkelrogstad** [comment]
There are a couple of things around the definitions of the Docker image itself: 
1. The LND images in Polar are downloaded from the LND GitHub. We compile LND ourselves, with custom compilation tags. 
2. In the future it's likely that we'll be using our own fork of LND, with custom functionality for channel capacities etc. 

Then there's also a few things concerning how the node is managed: 

1. We have an application backed by `bitcoind` and LND, so we need to coordinate the correct RPC and ZMQ credentials for communication between these three services. 
2. Defining `bitcoind` and LND as services in our own `docker-compose.yml` gives us control about how their lifecycles look like w.r.t other services in our setup. 

If it was possible to query/control Polar through some sort of CLI or RPC interface it is possible that the two points above could be remedied by that.

**Comment by jamaljsr** [comment]
Thanks for the clarification. I think I understand what you're doing. I do have a couple more questions:
1. You obviously are very knowledgable on LND/bitcoind configuration and commands. What benefit does Polar provide you in your development workflow? Is it the ability to easily create/destroy the networks or the visual graph view that is most helpful?
2. I plan to implement the ability to specify a custom local docker image to use for each node. This was requested in #255 and I briefly outlined my thoughts in the comments. Would this suffice for you use case or would further customizations be required?

**Comment by torkelrogstad** [comment]
1. I'd say the biggest benefit is easily creating and destroying networks. We want to test our application under different network conditions, which Polar is great for. Something we'd also love to use Polar for, is to emulate real LN activity in a local regtest network. Our development setup would then very closely mimic our production setup. The visual graph view is a nice bonus, but comes in second to easily defining networks. 

2. That depends a bit on how flexible the feature would end up being, but that could very well be the case. So might be a good idea to get that feature out of the way first. Let me know if there's anything I could do to help you out with that. Either implementation wise or with testing.

**Comment by jamaljsr** [comment]
Great! I do think the custom image feature would get you most of the way to what you need. It may just need a bit more tweaking. I'll keep this open and update you when I have something you can test.
