### ISSUE TITLE
Feature Request: Visualize inbound/outbound and route taken for a paiement

### ISSUE THREAD

**Issue by assaad** [jamaljsr/polar#290]
Hello, 
Awesome work, i am curious to know if it will be in the roadmap of the project to visualize the inbound/outbound capacity of channels and the routing road taken for a specific paiement. 
Many thanks!

**Comment by jamaljsr** [comment]
Hey @assaad, thanks for the suggestion.

The inbound/outbound capacity is currently displayed visually in the graph using the green & blue colors on the lines that connect the nodes. The colors will shift from one side to the other as payments are made through the channel. From the perspective of the node that opened the channel, green represents their outbound capacity and blue is the inbound capacity. The colors mean the opposite for the destination node. If you click on the line, you can view the exact capacities for the source and destination nodes in the sidebar.

![image](https://user-images.githubusercontent.com/1356600/73771588-a0dac580-474c-11ea-8de1-fa13c724789a.png)

Regarding payments, Polar does not currently track or display the routes that were used by payments. I'm not sure if this would be possible to add. LND does have the `listpayments` RPC that includes the path that the payment took, but c-lightning does not return the path in its `listpayments` RPC. I wouldn't want to include functionality in Polar that only works on one implementation. If you have any thoughts on where we can get this data to display in the UI, I am open to discussing further.

**Comment by jamaljsr** [comment]
Closing this as there isn't anything actionable to do here. Feel free to follow-up if necessary.
