### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by Alex2114** [jamaljsr/polar#291]
Advice from the developer

Polar is built using Electron which ultimately runs on NodeJS. It uses electron-builder to compile and package the app into an executable.

Packaging Polar on most linux distros should be possible. To do so, you will need to have Docker and NodeJS installed. You'll also need yarn installed globally using "npm install -g yarn".

1. Clone the repo: git clone https://github.com/jamaljsr/polar.git
2. Install dependencies: yarn install
3. Package the app: yarn package

This will create the .deb and .AppImage files in the dist/ folder which you can use to install or run Polar.

**Comment by jamaljsr** [comment]
Thanks @Alex2114. I will create a contributing document which describes how to get a Polar developer environment setup. It's pretty simple but I guess it shouldn't be assumed that everyone knows how to do it.

**Comment by Alex2114** [comment]
OK plaese do, it was bit daunting to see the code at 5 in the morning…
Beaglebone Black is like Raspberry Pi, but open source hardware, used in many miners
Thanks
 
Alex
  
>Wednesday, February 5, 2020 1:39 AM +03:00 from jamaljsr <notifications@github.com>:
> 
>Thanks  @Alex2114 . I will create a contributing document which describes how to get a Polar developer environment setup. It's pretty simple but I guess it shouldn't be assumed that everyone knows how to do it.
>—
