### ISSUE TITLE
wrong Spanish translation

### ISSUE THREAD

**Issue by grunch** [jamaljsr/polar#292]
Hi, in the spanish version we see this on hexadecimal format of the files.

![polar](https://user-images.githubusercontent.com/228364/74037606-5c923400-499d-11ea-81cc-a5ea7830ee0d.png)

This word means like `witchcraft`, hexadecimal in spanish is `hexadecimal`, so we can not translate that and just put hex or hexa

**Comment by jamaljsr** [comment]
Thanks for pointing out this translation error. I'll get this fixed for the next release.
