### ISSUE TITLE
Feature Request: Make bitcoind's ZeroMQ servers available on LAN

### ISSUE THREAD

**Issue by hsjoberg** [jamaljsr/polar#296]
Hey there. Awesome project! Helps a lot for experimenting and testing. :smiley:

I have a feature request I would like to discuss.  
Right now when running bitcoind, the node's ZeroMQ servers can only listen to incoming connections within the private network (172.x.x.x). I would like it to be available to the host, just like the REST server is.

The reason why I would like this is because when working on a Lightning Wallet, it's currently not possible to connect to the network on a real device, as that would not be on the host machine where the docker cluster is. (I would also like to have lnd's P2P server accessible on LAN, but I will open a separate issue and PR about that).

I am currently working on a solution for this.

This is related to #288.

Cheers
Hampus

**Comment by jamaljsr** [comment]
Hey @hsjoberg, this shouldn't be too difficult to add. I do not have any objections to making these ports available to the host. If you are going to work on adding this yourself, please be sure to use the port detection functionality to avoid conflicts on the host. The current detection for REST & GRPC ports can be found in [getOpenPorts](https://github.com/jamaljsr/polar/blob/master/src/utils/network.ts#L281) and [BasePorts](https://github.com/jamaljsr/polar/blob/master/src/utils/constants.ts#L45).

**Comment by hsjoberg** [comment]
@jamaljsr Thank you for your reply.
Yes I've already got used to the project's source code. :slightly_smiling_face: Happy to see someone else use `easy-peasy`. 
I'll have a PR up tonight or tomorrow so we can discuss and look at it further.

Best
