### ISSUE TITLE
Feature Request: Make Lighting nodes P2P connectivity available on LAN

### ISSUE THREAD

**Issue by hsjoberg** [jamaljsr/polar#298]
Right now when running an lnd or c-lightning node, the node can only listen to incoming connections within the private network (172.x.x.x). I would like it to be available to the host, just like the REST server is.  

The reason why I would like this is because when working on a Lightning Wallet, it's currently not possible to connect to the network on a real device, as that would not be on the host machine where the docker cluster is.

I am currently working on a solution for this.

This is related to #288.

Cheers
Hampus

**Comment by jamaljsr** [comment]
Hey @hsjoberg, fair enough request. Should be pretty straight forward to add.
