### ISSUE TITLE
Bug: "ENOENT: no such file or directory, open '<...filepath...>/lnd-2/tls.cert'"

### ISSUE THREAD

**Issue by valentinewallace** [jamaljsr/polar#304]
**Describe the bug**
https://i.imgur.com/KYDsspe.png
https://i.imgur.com/Ld9H8mD.png
https://i.imgur.com/XWGbALC.png
https://i.imgur.com/WPAILGi.png

```
Unable to connect to LND node
ENOENT: no such file or directory, open '/home/valentine/.config/polar/data/networks/1/volumes/lnd/lnd-2/tls.cert'
```
^ Also applies to lnd-1.
Bitcoind gets this error: 
```
Unable to connect to bitcoin node
connect ECONNREFUSED 127.0.0.1:18443
```

**To Reproduce**
1. Build polar from source on arch linux using `yarn package`
2. from the `dist` directory: `./polar-linux-x86_64-v0.2.1.AppImage`

**Expected behavior**
No error

**Desktop (please complete the following information):**
- OS: Arch Linux
- Polar Version: commit 55d604b7cda4af71526e1e0d4a0c1f577a5378f9
- Docker Version: 19.03.6-ce
- Docker Compose Version: 1.25.4

**Additional context**
love this project!

**Comment by jamaljsr** [comment]
Hey @valentinewallace thanks for the bug report.

Are you using a network that was created with an older version of Polar? The path where it looks for the cert had changed in v0.2.0 from `/home/valentine/.config/polar/data/networks` to `/home/valentine/.polar/networks`. I am not sure why it is still using that path. Maybe the migration at startup failed for some reason. 

Can you try creating a new network to see if that works?

**Comment by valentinewallace** [comment]
>Can you try creating a new network to see if that works?

That worked, thanks! 

> Are you using a network that was created with an older version of Polar?

Probably, I've had polar for a while. Probably not a common problem so feel free to close this issue if you prefer!

**Comment by jamaljsr** [comment]
Oh wow, I just realized the LND node names are `lnd-1` & `lnd-2`. You were using Polar even before the first release 🙀. The names were to alice, bob, carol... before v0.1.0. You are unfortunately the victim of early adopter syndrome. Starting a new network is the best cure for your ailment. 

Thanks for the early support 👍
