### ISSUE TITLE
lnd abandonchannel

### ISSUE THREAD

**Issue by nicolasburtey** [jamaljsr/polar#307]
It seems this feature is not available:

```
$lnd abandonchannel "channelid"
[lncli] rpc error: code = Unknown desc = AbandonChannel RPC call only available in dev builds
```

**Comment by jamaljsr** [comment]
We currently use the production builds of LND in the docker images. So this command is not available.

I just merged PR #299 which adds the ability to use a custom docker image, so it will be in the next release. With this, you'll be able to create images using any build of LND that suites your needs. 

Would this work for you?

**Comment by nicolasburtey** [comment]
yes, awesome.

don't know if there is debug build available, but if there is would be
great to point it out in the doc!

**Comment by jamaljsr** [comment]
There isn't a debug build available to download, but you can compile it yourself from the source code. Check out the [CONTRIBUTING](https://github.com/jamaljsr/polar/blob/master/CONTRIBUTING.md) docs for details on how to do that.

**Comment by jamaljsr** [comment]
Closing this now. Let me know if you have any other questions.
