### ISSUE TITLE
Bug: display of commands seems it in in erase mode (versus insert)

### ISSUE THREAD

**Issue by nicolasburtey** [jamaljsr/polar#308]
**Describe the bug**
The display of characters in the command line is like in "overwrite" mode instead of "insert" new caracters

**To Reproduce**
Write a command in the one of the shell shell
Use Up arrow, the display is all messed by mixing current and past command. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11156370/75577439-d48cd080-5a16-11ea-97c6-476bb266794a.png)

**Desktop (please complete the following information):**
- OS: OSX Catalina
- Polar Version: 0.2.0
- Docker Engine: 19.03.5
- Docker Compose Version: 1.25.4

**Comment by jamaljsr** [comment]
Hey @nicolasburtey  

I have also seen this behavior myself.  I just haven't gotten around to fixing it yet. Thanks for the bug report.
