### ISSUE TITLE
Feature Request: Polar CLI

### ISSUE THREAD

**Issue by nepet** [jamaljsr/polar#324]
**Is your feature request related to a problem? Please describe.**
For automated testing of applications that require a LND network on a ci-server we can not use a GUI.

**Describe the solution you'd like**
A CLI (or any form of api) covering the basic functionality of polar, especially the creation of networks in a certain state (maybe by network import) without the need of a graphical user interface and electron. This would be a helpful solution when someone needs to automatically spawn different LND network configurations for testing.

Cheers, 
Peter

**Comment by jamaljsr** [comment]
Hi @nepet, I have heard a similar request before. It's a great idea that I do hope makes it into the project one day. This would be a pretty substantial change to the plumbing of how Polar works now, and I personally cannot commit to implementing this in the near future. Obviously, PR's are welcomed.

In the meantime, have you seen the [simverse](https://github.com/darwin/simverse) project? It is a command line tool using docker with scripting capabilities and no GUI. It has support for all of the major LN implementations, bitcoind & btcd. I think this may be able to satisfy your needs today.

**Comment by nepet** [comment]
Hi @jamaljsr, Thanks for your fast response. I didnt know about simverse. Thanks for the hint I will give it a shot.

**Comment by jamaljsr** [comment]
I'm going to close this for now as I cannot commit to taking any action on it.
