### ISSUE TITLE
Bug: Unable to view Polar in the browser when building from source

### ISSUE THREAD

**Issue by nickycutesc** [jamaljsr/polar#333]
**Describe the bug**

After successfully building from source, I'm presented with this information:

Starting the development server...
Compiled successfully!
You can now view polar in the browser.
Local:            http://localhost:3000
On Your Network:  http://10.0.1.5:3000

I try to view the http:// addresses in my browser, but all I see is a blank screen. I tried putting the address into other browsers, with no cookies blocking....but I still keep getting a blank screen.

**To Reproduce**
1. git clone https://github.com/jamaljsr/polar.git
2. cd polar
3. yarn
4. yarn dev

**Expected behavior**

See polar in the browser.

**Screenshots**

Blank screen:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/24903257/78317075-4cc34600-752f-11ea-8dbe-da8963a3ff8e.png">

**Desktop (please complete the following information):**
- OS: macOS Catalina 10.15.4
- Polar Version: 1.0.0
- Docker Version: Community 2.2.0.4(43472)
- Docker Compose Version: 1.25.4

**Additional context**

**Comment by jamaljsr** [comment]
Hey @nickycutesc, 

Polar won't run in the browser. That local web server is only used for development to be able to reload the app quickly without needing to re-package after every code change. 

When you run `yarn dev`, you should see an Electron app window open on your desktop which contains loads the React app inside of it. If this window is not opening for you, can you please paste the full terminal log output?

**Comment by nickycutesc** [comment]
Hey @jamaljsr 

I am able to see the Electron app window. Thanks for the explanation and all the best with @lightning!

**Comment by jamaljsr** [comment]
Ok, great.

And thank you!
