### ISSUE TITLE
Problem installing docker on Ubuntu from .deb

### ISSUE THREAD

**Issue by johnpaulkiser** [jamaljsr/polar#336]
_Opening/Closing an issue to document a common error Ubuntu & other linux users may face when installing Docker for Polar._  

### Error: 
```
Docker Error
connect EACCES /var/run/docker.sock
```

Receiving this error after installing docker means that Polar is running without root privileges while docker requires root privileges.

### Solution:
After installing docker & docker compose like normal, create a Unix group to add users to that need docker root privileges. 
```
$ sudo groupadd docker
$ sudo usermod -aG docker $USER
```
Then logout and login and you should see Polar working correctly.   

Full tutorial [here.](https://docs.docker.com/engine/install/linux-postinstall/)

**Comment by jamaljsr** [comment]
Thank you for documenting this problem. 👌
