### ISSUE TITLE
Bug: Can't connect to LND container from other container

### ISSUE THREAD

**Issue by boufni95** [jamaljsr/polar#352]
**Describe the bug**
When I try to create a new container that uses GRPC to connect to LND, I get error 14

**To Reproduce**
1. Create a network with Polar
2. Try to connect to LND via GRPC from another container
3. See error

**Expected behavior**
The connection works without errors

**Desktop (please complete the following information):**
- OS: Windows 10 v2004
- Polar Version: 1.0.0
- Docker Version: 19.03.8
- Docker Compose Version: 1.25.5

**Additional context**
The problem is in the default settings used to run the node
```
lnd
  --noseedbackup
  --trickledelay=5000
  --alias={{name}}
  --externalip={{name}}
  --tlsextradomain={{name}}
  --listen=0.0.0.0:9735
  --rpclisten=0.0.0.0:10009
  --restlisten=0.0.0.0:8080
  --bitcoin.active
  --bitcoin.regtest
  --bitcoin.node=bitcoind
  --bitcoind.rpchost={{backendName}}
  --bitcoind.rpcuser={{rpcUser}}
  --bitcoind.rpcpass={{rpcPass}}
  --bitcoind.zmqpubrawblock=tcp://{{backendName}}:28334
  --bitcoind.zmqpubrawtx=tcp://{{backendName}}:28335
```
the flag `--tlsextradomain` needs to contain the name of the container but instead, it contains the alias of the node
I solved by adding this to the default `--tlsextradomain=polar-n2-{{name}}` which works because I'm using the second network, but it's not a fix

**Comment by jamaljsr** [comment]
Hi @boufni95, thanks for the detailed bug report and for providing your workaround. The `tlsextradomain` value is indeed incorrect. I'll get this fixed before the next release.
