### ISSUE TITLE
Bug: All my LND nodes stopped starting up

### ISSUE THREAD

**Issue by AnthonyRonning** [jamaljsr/polar#362]
**Describe the bug**
Have a network of 2 LND 10.0, 1 LND 10.1, and a clightning and an eclair. Been working fine for a few weeks, however today, even after restarting, I can't get my LND nodes to start up. Getting the same error on all of them. 

Polar error: `14 UNAVAILABLE: failed to connect to all addresses`

Docker error: 
```
2020-07-15 17:14:45.681 [WRN] LTND: open /home/lnd/.lnd/lnd.conf: no such file or directory

2020-07-15 17:14:45.684 [INF] LTND: Version: 0.10.1-beta commit=v0.10.1-beta, build=production, logging=default

2020-07-15 17:14:45.687 [INF] LTND: Active chain: Bitcoin (network=regtest)

2020-07-15 17:14:45.688 [INF] LTND: Opening the main database, this might take a few minutes...

2020-07-15 17:14:45.744 [INF] CHDB: Checking for schema update: latest_version=13, db_version=13

2020-07-15 17:14:45.744 [INF] LTND: Database now open (time_to_open=53.485239ms)!

2020-07-15 17:14:46.151 [INF] LTND: Primary chain is set to: bitcoin

2020-07-15 17:14:46.185 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 172.20.0.2:28335

2020-07-15 17:14:46.185 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 172.20.0.2:28334

2020-07-15 17:14:51.071 [INF] LNWL: Opened wallet

2020-07-15 17:14:53.490 [INF] LNWL: The wallet has been unlocked without a time limit

2020-07-15 17:14:53.919 [INF] LTND: LightningWallet opened

goroutine 101 [running]:

github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000442780)
```

is it the `no such file or directory` that's causing the issue? Really don't know how to reproduce this, everything had been pretty standard usage until I start it up today. 

Note: I can create new LND nodes (10.1) and they seem to work fine. 

Wanted to reach out here first before the LND repo just to see if it was something Polar specific that might have messed up. 

**Screenshots**
<img width="1365" alt="Screen Shot 2020-07-15 at 11 24 24 AM" src="https://user-images.githubusercontent.com/10763569/87575867-cbcb2d00-c68d-11ea-901a-be05b2f58aab.png">

**Desktop (please complete the following information):**
- OS: OSX Catalina
- Polar Version: 1.0.0
- Docker Version: 19.03.8
- Docker Compose Version:  1.25.4

**Additional context**

**Comment by jamaljsr** [comment]
Hey @AnthonyRonning,

I think this may be a Polar bug. I have a couple of questions.

1. What's the version of the bitcoin node in this network?
1. If you create a new network, will LND nodes start up successfully?

**Comment by AnthonyRonning** [comment]
> What's the version of the bitcoin node in this network?

`v0.19.1`

> If you create a new network, will LND nodes start up successfully?

For some reason I can't create a new network. Tried restarting a couple times, but the button doesn't do anything. 
<img width="1375" alt="Screen Shot 2020-07-15 at 12 14 31 PM" src="https://user-images.githubusercontent.com/10763569/87580449-c8876f80-c694-11ea-9714-be6e759775d6.png">

**Comment by jamaljsr** [comment]
Can you update to Polar v1.0.1? I think I may have accidentally broke earlier versions when adding support for bitcoind v0.20.0.

**Comment by AnthonyRonning** [comment]
Oh cool, that seemed to work! Sorry, I was not aware there was an update. Only weird thing is that those channels aren't showing up right now in the GUI, but shows up in Zap (perspective of Erin). Restart (both app and network) didn't seem to pick up awareness. NBD though. 

<img width="1013" alt="Screen Shot 2020-07-15 at 1 09 29 PM" src="https://user-images.githubusercontent.com/10763569/87585849-e48f0f00-c69c-11ea-9ffd-9f7c09cf5287.png">

<img width="882" alt="Screen Shot 2020-07-15 at 1 10 50 PM" src="https://user-images.githubusercontent.com/10763569/87585854-e8229600-c69c-11ea-9008-259084646523.png">

**Comment by jamaljsr** [comment]
Awesome! Glad that worked.

To fix the channel issue, just click on the canvas so none of the nodes are selected. Then click on the refresh icon on the top right of the sidebar. This resets the channels in the designer to match what is reported by the nodes. Sometimes it gets out of sync.

**Comment by AnthonyRonning** [comment]
<img width="1011" alt="Screen Shot 2020-07-15 at 1 23 47 PM" src="https://user-images.githubusercontent.com/10763569/87586837-6d5a7a80-c69e-11ea-818b-b262671bf387.png">

Beautiful! I had thought that refresh button just pulled down new versions (forgot that's at the bottom). Thanks so much!
