### ISSUE TITLE
Bug: removed lightning nodes don't disappear from UI

### ISSUE THREAD

**Issue by losnappas** [jamaljsr/polar#365]
**Describe the bug**
A couple of times I had this bug where my c-lightning nodes wouldn't start up, giving me errors related to the socket or whatever. I removed those nodes and added new ones, which worked, but now I've got "alice" and "bob" - the nodes I removed - just hanging around.

This isn't a major issue, but I thought I'd post it anyways. The bigger issue might be that my nodes don't start up after rebooting my VM, but I'm not sure if that is caused by Polar, or by me, so I'm not here to report that now.

**To Reproduce**
In all honesty, I don't have a good way of reproducing this. I think maybe my file permissions were/are wrong, or it's because my VM setup or something.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 in a VM
- Polar Version: 1.0.1
- Docker Version: 20...something, gotta check back on this
- Docker Compose Version: TODO

**Additional context**
When I click on "alice", it acts like as if alice isn't even there, taking me to the default view with node selections.

**Comment by jamaljsr** [comment]
Hey @losnappas this is an interesting issue you are running into. Without being able to reproduce the issue, it'll be a bit challenging to find a solution, but I'm open to giving it a shot.

It sounds like the issue occurs after rebooting your VM. I've also ran into issues when I reboot my machine without stopping the Polar network first. Docker doesn't always shutdown the containers gracefully and when it starts them after the reboot, the daemons (c-lightning, LND, bitcoind) do not operate properly. Do you always stop the network in Polar before rebooting?

**Comment by losnappas** [comment]
> Do you always stop the network in Polar before rebooting?

I definitely haven't. Sometimes I hit the 'x' on the virtualbox vm window and shut it down that way, giving no regard to programs running. That said, I did stop it a couple of times before it shutting down, but it did not fix the ghost nodes, and I can't recall if it helped with the nodes not starting or not.

It's a bit too much effort to go rebooting the vm just to try this out, since it takes so long for it to start, but I'll try paying more attention when I do.

**Comment by jamaljsr** [comment]
Ok. I believe that may be the issue but there's no way to know for sure without testing it. I would highly recommend first stopping all Polar networks before shutting down the VM in the future. 

In regards to the current ghost nodes you have, I suggest deleting the network and create a new one. I don't think this broken network can easily be repaired.

Thanks for the bug report. Appreciate it 👍
