### ISSUE TITLE
Question: How to connect to lightning nodes from remote mobile app?

### ISSUE THREAD

**Issue by mykhailo-gaidai** [jamaljsr/polar#373]
Excuse me for the stupid question, but is there a way to allow lightning nodes to accept connections from the local network (using host ip as external one)?
For example, how to connect to any lightning node using mobile wallet app?

**Comment by mykhailo-gaidai** [comment]
Connecting to lnd node from mobile app can be achieved by port forwarding from mobile to the machine where Polar is running
The question was quite stupid indeed :)

**Comment by jamaljsr** [comment]
@mykhailo-gaidai not a stupid question at all. I've been asked this a few times already. Port forwarding or SSH tunneling is the approach I would recommend. I'm glad you were able to figure this out yourself. 👍
