### ISSUE TITLE
Doc: The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [jamaljsr/polar#392]
**Describe the bug**
The README file in this repo has a bad link - [404:NotFound]

The markup version of the readme that is displayed for the main page in this repo contains the following link:
Status code [404:NotFound] - Link: https://github.com/jamaljsr/polar/releases/download/v1.0.1/polar-mac-v1.0.1.zip  (zip)

(The link in the readme’s raw markdown may appear in a different format to the link above)

**To Reproduce**
Click the link under "zip"

**Expected behavior**
Link should work

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.
If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by bolatovumar** [comment]
I don't think there is a special link for a zip file for Mac specifically. There is a zip file of the source code, however: https://github.com/jamaljsr/polar/archive/v1.0.1.zip

**Comment by jamaljsr** [comment]
Good catch. I have removed (https://github.com/jamaljsr/polar/commit/346fa54d4f00efd8203d944c61d5d269c7418099) the ZIP file download link for Mac since this version is not included in releases.
