### ISSUE TITLE
Unable to build. New release?

### ISSUE THREAD

**Issue by michaelWuensch** [jamaljsr/polar#402]
**Describe the bug**
I am unable to run or package the project on my system.

**To Reproduce**
Probably this happens only on my system but I did the following:
1. Installed all prerequisites. (Official 1.01 release is running on my machine)
2. cloned the repo
3. yarn
4. "yarn dev" or "yarn package" both throw errors

yarn dev throws the following error:
```
TSError: ⨯ Unable to compile TypeScript:
[dev:electron] electron/utils/zip.ts(40,32): error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
```

"yarn lint:all" throws 35 errors as well

**Expected behavior**
no errors

**Desktop (please complete the following information):**
- OS: Linux Manjaro
- Polar Version: master, commit: 4fbad43ec634793b07fb3b515ba9e972fcfe19af
- Docker Version: 19.03.13-ce, build 4484c46d9d
- Docker Compose Version: 1.27.4

**Additional context**
An up to date release would also help me so I can test with LND 0.11.1

**Comment by jamaljsr** [comment]
Hey @michaelWuensch, I've tested on my machine and it builds properly. I also see that the [CI builds](https://github.com/jamaljsr/polar/actions/runs/398230230) for commit [4fbad43](https://github.com/jamaljsr/polar/commit/4fbad43ec634793b07fb3b515ba9e972fcfe19af) completed successfully as well. 

That error makes me believe your terminal may be using the wrong version of Typescript. It should be `v4.0.5` when you run `yarn tsc --version`.

Regarding LND `v0.11.1`, this version is available in Polar now. You just need to click the "Check for new Node Versions" in the sidebar. This link is at the bottom of the sidebar when you enable the "Show All Versions" toggle.

Let me know if you're still not able to get it working.

**Comment by michaelWuensch** [comment]
@jamaljsr thanks for your help! Didn't know i can get the new images so easily, that is fantastic!
The version returned in my terminal is 4.1.2

**Comment by jamaljsr** [comment]
Ah ok, you are using a newer version of typescript which does raise an error. I'll need to update the code to make it compatible with that version. There's already a failing PR (#397) which I need to address.

I'm glad you were able to get it working with the released binary. Best of luck on your project 👍
