### ISSUE TITLE
Bug: Compile error when running `yarn dev`

### ISSUE THREAD

**Issue by murtyjones** [jamaljsr/polar#403]
**Describe the bug**

Working from the instructions in the contributing doc, I ran into this compile error when setting up my environment:
```
[dev:app] Failed to compile.
[dev:app] 
[dev:app] ./src/utils/network.ts
[dev:app]   Line 0:  Parsing error: Cannot read property 'map' of undefined
```

**To Reproduce**
1. Clone the repo
1. `yarn`
1. `yarn dev`

**Expected behavior**
App starts up

**Screenshots**
![image](https://user-images.githubusercontent.com/708562/101551216-b2998480-397e-11eb-9b71-c8b8f4f4fc36.png)
![image](https://user-images.githubusercontent.com/708562/101552966-c98da600-3981-11eb-8c95-4a31883ebf67.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina v10.15.7
- Polar Version: master
- Docker Version: 19.03.13
- Docker Compose Version: 1.27.4

**Additional context**
N/A

**Comment by jamaljsr** [comment]
Hey @murtyjones what version of `node` do you have installed?

**Comment by murtyjones** [comment]
> Hey @murtyjones what version of `node` do you have installed?

Hey there, I'm running 10.22.0

```
$ nvm which current
/Users/me/.nvm/versions/node/v10.22.0/bin/node
```

**Comment by jamaljsr** [comment]
Could you try switching to v12.x or v14.x? I have a hunch that may be the problem.

**Comment by bolatovumar** [comment]
I wonder it it makes sense to specify the `engines` field to be explicit about what version of Node is expected? https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

**Comment by murtyjones** [comment]
Yeah I was wondering if an upgrade was needed too. Unfortunately node v12.20.0 and 14.15.1 produce the same error. Can't make much of the stack trace

**Comment by bolatovumar** [comment]
I just tried it and I'm running into the same issue. Using Node **v12.16.2** and Yarn **v1.22.0**.

![Screen Shot 2020-12-08 at 6 55 39 PM](https://user-images.githubusercontent.com/1934678/101568237-22ac0880-3987-11eb-965a-77831ade6513.png)

**Comment by jamaljsr** [comment]
Oh wow! I see the issue now. It was working fine until I deleted the `node_modules` folder. I will investigate. Thanks for notifying me of the problem.

**Comment by jamaljsr** [comment]
I think I've found and fixed the issue in https://github.com/jamaljsr/polar/pull/404. Can you checkout this branch and see if you are able to run the app without getting that error?

**Comment by murtyjones** [comment]
@jamaljsr On that branch the error seems to have gone away – unfortunately only to be replaced by a new one 😞 
![image](https://user-images.githubusercontent.com/708562/101626090-6c7a0a80-39ea-11eb-9bba-86ea4676469e.png)

**Comment by murtyjones** [comment]
Actually, it looks like it works if I delete the `node_modules` folder and rerun `yarn` and then `yarn dev` 👍

**Comment by jamaljsr** [comment]
Excellent! thanks for testing.

**Comment by murtyjones** [comment]
thank you @jamaljsr!

**Comment by bolatovumar** [comment]
@murtyjones @jamaljsr I'm just trying to run `yarn dev` now and I'm getting the same error @murtyjones was getting above (https://github.com/jamaljsr/polar/issues/403#issuecomment-741721442). I cloned the repo fresh so there shouldn't have been issues with any stale packages in `node_modules`. I have also deleted the `node_modules` folder and ran `yarn` a few times to same effect.

I'm running Node v12.16.2 and Yarn v1.22.0
 
![Screen Shot 2021-02-07 at 2 57 00 PM](https://user-images.githubusercontent.com/1934678/107162218-871f2000-6956-11eb-8979-1ff7e91891ac.png)

**Comment by jamaljsr** [comment]
Very strange. I'm not able to replicate the issue on my Mac or Windows machines.

I have Node v12.18.0 and Yarn v1.22.4. 
I ran the following and it works for me:
```
rm -rf node_modules/
yarn cache clean
yarn
yarn dev
```

Can you try deleting your `yarn.lock` file then running `yarn` again? Maybe there is some issues with the dependencies of dependencies that somehow I'm not seeing.

**Comment by bolatovumar** [comment]
> Very strange. I'm not able to replicate the issue on my Mac or Windows machines.
> 
> I have Node v12.18.0 and Yarn v1.22.4.
> I ran the following and it works for me:
> 
> ```
> rm -rf node_modules/
> yarn cache clean
> yarn
> yarn dev
> ```
> 
> Can you try deleting your `yarn.lock` file then running `yarn` again? Maybe there is some issues with the dependencies of dependencies that somehow I'm not seeing.

@jamaljsr tried all of the steps above and also updated my Node to version 12.18.0 just to make sure. Get the same error no matter how many times I try.

![Screen Shot 2021-02-10 at 6 21 59 PM](https://user-images.githubusercontent.com/1934678/107596589-1170b980-6bcd-11eb-97de-fc13cf559470.png)
![Screen Shot 2021-02-10 at 6 22 05 PM](https://user-images.githubusercontent.com/1934678/107596593-146baa00-6bcd-11eb-98b6-fc394857f918.png)
![Screen Shot 2021-02-10 at 6 22 08 PM](https://user-images.githubusercontent.com/1934678/107596594-146baa00-6bcd-11eb-81de-916762d2379d.png)

**Comment by jamaljsr** [comment]
I think the problem may be with outdated React DevTools plugins in your local Electron installation. Can you clear your Electron folder to clean up possibly stale data.
```
rm -rf ~/Library/Application\ Support/Electron/
```

**Comment by bolatovumar** [comment]
@jamaljsr alright, running `rm -rf ~/Library/Application\ Support/Electron/` fixed it.
