### ISSUE TITLE
Bug/Question: using yarn cm

### ISSUE THREAD

**Issue by murtyjones** [jamaljsr/polar#405]
This is probably a user issue, but I'm trying to commit a change on a fork and hitting some obscure error in using `yarn cm`
![image](https://user-images.githubusercontent.com/708562/101706353-e34ced00-3a56-11eb-9ede-5eb0147f5a5c.png)

**Comment by jamaljsr** [comment]
Yes, I know this hasn't worked for some time. I assume one of the dependency updates broke it.

Personally, I've just stop using it for the time being. The traditional `git commit -m "..."` still works fine. 

I'll either figure out how to fix it or just remove `yarn cm` from the scripts.

**Comment by jamaljsr** [comment]
`yarn cm` was removed some time ago.
