### ISSUE TITLE
Feature Request: An example of using polar 

### ISSUE THREAD

**Issue by murtyjones** [jamaljsr/polar#408]
Firstly, I just want to say that Polar is awesome and I'm really excited that a tool like this exists for the ecosystem!

I've been playing with it for the last few days, trying to get a working script that allows Alice to open a channel with Bob. Doing so, at least in my chosen language (TypeScript) was trickier than I thought it'd be.

For new developers who are unsure where to get started, a simple working example in the repo would go a long way. What I'd like to propose is this script to an `examples` folder in the repo, which would looks something like this:

```ts
import ln from 'ln-service';
import { ALICE_LND_AUTH } from './config';

const openChannel = async (lnd: ln.AuthenticatedLND) => {
  const { peers } = await ln.getPeers({ lnd });
  const args: ln.OpenChannelArgs = {
    local_tokens: 100000,
    partner_public_key: peers[0].public_key,
  };
  return ln.openChannel({ lnd, ...args });
};

(async () => {
  const { lnd } = ln.authenticatedLndGrpc(ALICE_LND_AUTH);
  try {
    const { pending_channels } = await ln.getPendingChannels({ lnd });
    if (!pending_channels.length) {
      const { transaction_id } = await openChannel(lnd);
      console.log('No pending channels found, opened one: ', transaction_id);
    }
    console.log('Pending channels found: ', pending_channels.length);
  } catch (err) {
    console.error(err);
  }
})();
```

It's a really simple script, so it might not seem all that useful, but I think it'd be a good starting point for a couple of reasons:
- Having an example of a working TypeScript gRPC client is good for new developers. The state of various LND gRPC libraries' support for TypeScript requires some hacking to get type definitions (in my case, using [`ln-service`](https://github.com/alexbosworth/ln-service) + [`patch-package`](https://www.npmjs.com/package/patch-package) to add types from a [not-yet-merged PR](https://github.com/alexbosworth/ln-service/pull/135)). So this project would be a useful way to illustrate the bootstrapping needed for a new developer who wants to use a popular language like TS.
- Showing how the outputs from Polar (e.g. gRPC connection info, TLS, macaroons) are meant to be used to authenticate with a lightning client

In the future, such an example would ideally be extended to a simple interactive interface that lets developers play with introducing real app-like functionality.

I'm happy to clean up what I have and put it in PR, but want to get some feedback before I do so and see if this would be useful.

**Comment by jamaljsr** [comment]
Hey @murtyjones thanks for all of the feedback and for opening an issue first before creating a PR. 

I certainly agree that sample code would be great to help new devs get started working with the lightning nodes. I had a bit of a bigger vision however. I wanted to create sample apps instead of just code snippets. The apps would still be pretty simple. Maybe just fetching the list of open channels. But I'd want to write the apps in multiple languages (TS/JS, Python, C#, Go, Java) and also for each of the three implementations. So that's about 15 apps. I also imagined that there would be some UI in Polar to preview and download the apps locally, instead of them just being hosted on GitHub. Obviously, my grand vision will take a fair bit of effort to complete. That's probably why I haven't done it already. 

As much as I'd love to accept your suggested contribution, I think I'd prefer if the addition was more wholistic and didn't targeted at any specific language or Lightning implementation.

**Comment by murtyjones** [comment]
Thanks for sharing some context.

What you're saying makes sense to me, although I'd suggest that some of these steps can be done incrementally. For example, starting with a TS/JS example for each of the three implementations wouldn't prevent the other language samples being added later on. I suggest this only because I'd be happy to help by working on those sample TS apps so that there's something for developers to reference

**Comment by jamaljsr** [comment]
I think that's a fair compromise. We have to start somewhere. Maybe having some TS samples will encourage others to contribute the additional languages.

Just an FYI, if you aren't aware, there's the [RadarTech/lnrpc](https://github.com/RadarTech/lnrpc) npm module that can be used to connect to `lnd`. It has types built-in and is updated regularly for new releases. This is what Polar uses to connect to the nodes.

**Comment by murtyjones** [comment]
Cool, sounds good! I'll take a look at it and ideally would like to share some kind of an outline before I get too far into implementation.

I'll take another look at `lnrpc`. There was an [issue](https://github.com/RadarTech/lnrpc/issues/80) when I tried it last week but it's since been fixed 🚀

**Comment by murtyjones** [comment]
For the "app" functionality, I was thinking of proposing something using an interactive terminal, as opposed to a web app or electron app that would complicate the example project structure. But curious to hear what you think @jamaljsr?

![image](https://user-images.githubusercontent.com/708562/102562520-3cdf9800-40a5-11eb-8fa9-78480a155906.png)

**Comment by jamaljsr** [comment]
Good idea 👍 

This removes the need for a frontend web framework which can add a bunch of code unrelated to Lightning. Your approach sounds good to me.
