### ISSUE TITLE
Allow to manage remote networks 

### ISSUE THREAD

**Issue by lessless** [jamaljsr/polar#415]
**Is your feature request related to a problem? Please describe.**
No it's not. 

**Describe the solution you'd like**
I want to manage remote networks.  

Right now Polar allows managing only local networks, but it's awesome that I want to be able to manage my staging networks as well. 
And allow beta-users/testers to pay their invoices inside that network! 

**Additional context**
Imagine I'm developing a LN web app. I can use Polar locally but when it's time to launch on staging I'm back into brin your own infrastructure game. 
And it's not worth it. Especially after having Polar taking care of that locally. 

I'd love to setup a server with docker and then somehow create "remote networks" in Polar.

**Comment by jamaljsr** [comment]
Hey @lessless, this is an interesting suggestion. 

It may be a bit out of scope for using Polar as a developer tool, but I'm curious what you envision the staging environment to look like. Do you want to run regtest nodes, or maybe testnet? Would this be running on a cloud-based machine with no UI? Can you tell me more about how the "remote network" would be setup?

**Comment by lessless** [comment]
> Do you want to run regtest nodes, or maybe testnet?

Can you please explain the difference? 

> Would this be running on a cloud-based machine with no UI? 

Yes

> Can you tell me more about how the "remote network" would be set up?

As a user, when I create a new network I want to be able to select whether it's local or remote. 
Then, if it's a remote network I want to be able to enter some credentials. After that everything should stay exactly the same. 

It's totally reasonable that I have to set up a remote machine to be compatible with this feature. 
For example:
  - install docker
  - setup key-bases ssh authentication

Maybe docker contexts can come in handy https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/

I will have to set up a staging environment for my upcoming product next month or so and will be happy to be a tester or contribute as much as I can.

**Comment by jamaljsr** [comment]
> Can you please explain the difference?

https://developer.bitcoin.org/examples/testing.html contains a good explanation of the differences between testnet and regtest. Polar runs it's bitcoin & lightning nodes in regtest mode. The networks are self-contained with their own individual blockchains that are not compatible with the public bitcoin testnet network.

> I will have to set up a staging environment for my upcoming product next month or so and will be happy to be a tester or contribute as much as I can.

While this is an interesting idea, I still don't quite understand why you would want to run a Polar regtest network in a staging environment. I think you should use the tesnet network for staging. It's not a simple to setup as Polar is, but it's interoperable with all other products and services online that support testnet. The environment is a much closer representation of mainnet.

**Comment by lessless** [comment]
Hm. Maybe you're right! 
My reasoning is that it's super easy - a few clicks and off you go. 

But running it on testnet would be closer to production. Thanks for the tip!

**Comment by jamaljsr** [comment]
Thanks for understanding. I'll close out this issue now.
