### ISSUE TITLE
Feature Request: Open private channels

### ISSUE THREAD

**Issue by michaelWuensch** [jamaljsr/polar#425]
**Is your feature request related to a problem? Please describe.**
For testing purposes it would be awesome to easily create private channels in polar

**Describe the solution you'd like**
When opening a channel in polar it would be cool if there was a simple checkbox named "private" which should be unchecked by default.
Private channel lines could be displayed semitransparent in the view graph.

**Additional context**
I am testing stuff where I need to know if routes over private channels are found.

**Comment by jamaljsr** [comment]
This should be pretty easy to add. I also agree it would be cool to add some transparency to the channels in the graph so that they easily stand out. Thanks for the feedback 👍

**Comment by bolatovumar** [comment]
I wouldn't mind looking into this but I'm getting an error when running the dev version of Polar (left a comment here: https://github.com/jamaljsr/polar/issues/403#issuecomment-774785563).

**Comment by bolatovumar** [comment]
Started working on this.
