### ISSUE TITLE
Feature Request: Consider adding a short tutorial in lnbook

### ISSUE THREAD

**Issue by keblek** [jamaljsr/polar#435]
I added a small shoutout to the project in the new lnbook 

https://github.com/lnbook/lnbook/pull/645

It's a small tip, if someone here has an interesting idea for a short tutorial to do in polar then consider making a contribution.

In all fairness, polar is super simple to use so after the reader is done working with docker in the command line they can use polar very quickly.

**Comment by jamaljsr** [comment]
Closing this as the book has already been released with the tip included. Thanks so much for the contribution.
