### ISSUE TITLE
Creating Channels Hangs on M1 MacBook 

### ISSUE THREAD

**Issue by joelklabo** [jamaljsr/polar#442]
**Describe the bug**
When creating a test network with two LND nodes and one bitcoind I am able to deposit funds, mine blocks etc. but creating a channel seems to hang. This may only be an issue with the UI, not sure.

**To Reproduce**
Steps to reproduce the behavior: (following the Lapp tutorial on docs.lightning.engineering)
1. Create two LND nodes, one bitcoind node
2. Deposit funds in to Alice LND node
3. Create outgoing channel 250,000 capacity to bob node
4. Spinner spins forever and channel doesn't seem to be created.

**Expected behavior**
Channel would be created and reflected in the UI.

**Screenshots**
<img width="901" alt="Screen Shot 2021-03-24 at 2 07 39 PM" src="https://user-images.githubusercontent.com/264977/112383853-e472f480-8caa-11eb-890c-903198ba969d.png">

**Desktop (please complete the following information):**
- OS: macOS BigSur (MacBook Air M1)
- Polar Version: 1.2.0
- Docker Version: 20.10.5
- Docker Compose Version: 1.28.5

Logs attached here:
[renderer.log](https://github.com/jamaljsr/polar/files/6200493/renderer.log)
[main.log](https://github.com/jamaljsr/polar/files/6200492/main.log)

**Comment by joelklabo** [comment]
Did a little more looking around and saw `emu: uncaught target signal 11 (Segmentation fault) - core dumped` in the log of the LND node that was no longer updating blocks so this probably isn't a Polar issue. 

More info here in case anyone else reports it: https://github.com/docker/for-mac/issues/5123

Doesn't seem to be a solution currently.

**Comment by jamaljsr** [comment]
Thanks for the additional information on the root cause of the issue. Sad to hear that there's no solution yet on the docker side. Hopefully it can get resolved soon.

**Comment by axelclark** [comment]
@joelklabo is this issue fixed or did you find a work around?

**Comment by joelklabo** [comment]
I haven't tried again but it seemed to be an issue with docker on the M1 at
the time and nothing to do with Polar.

**Comment by RooSoft** [comment]
With an image created using [these instructions](https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md#LND), it is possible to use a LND node flawlessly on a Apple Silicon computer.

**Comment by RooSoft** [comment]
> With an image created using [these instructions](https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md#LND), it is possible to use a LND node flawlessly on a Apple Silicon computer.

The working image has of course been built on an M1 Mac....
