### ISSUE TITLE
Feature Request: Expose c-lightning rpc socket directly

### ISSUE THREAD

**Issue by f-hayek** [jamaljsr/polar#476]
**Is your feature request related to a problem? Please describe.**
I'm trying to develop an app for c-lightning using Polar but noticed it uses RTL Rest endpoint (plugin).
It's slow (an order of magnitude slower than my Go app talking to the socket directly) and it doesn't support every feature that's exposed via the socket directly (eg other plugins that are available via the rpc)
so I don't want to use it and don't want to make it a requirement for the users.

**Describe the solution you'd like**
Expose the c-lightning `lightning-rpc` socket on a port accessible outside Docker.
For example the following command will bind the socket to port 9737:

`socat TCP-LISTEN:9737,reuseaddr,fork UNIX-CONNECT:lightning-rpc`

What remains is mapping the container port to the host port.

**Additional context**
I don't know if LND,Eclair use a similar socket for RPC calls. If so it would make sense to expose it too, if not make it c-lightning option only.

**Comment by jamaljsr** [comment]
Thanks for the feedback @f-hayek 👍 

I recall spending a bunch of time attempting to get the `lightning-rpc` Unix socket to bind to a port of the Docker container using `socat`. Unfortunately, I was not successful and opted to use the `c-lightning-REST` plugin by RTL. It was pretty simple to implement and provided the basic functionality. I'd love to be able to make the `lightning-rpc` socket available to Polar users, if it is possible. I currently don't have the time to dive deep into it.

If you'd like to help out with the Docker & socket stuff, I'd be ok with making the necessary UI changes. The current Dockerfile that Polar uses is located in https://github.com/jamaljsr/polar/tree/master/docker/clightning. Would you be able to get the container listening on a port, without updating the Polar UI?

**Comment by f-hayek** [comment]
Thanks for the reply @jamaljsr - I'll look into it.

**Comment by aaronhayes** [comment]
@jamaljsr are you using a mac by any chance? 

Sharing arbitrary unix sockets is not supported on Mac. https://github.com/docker/for-mac/issues/483#issuecomment-758836836

**Comment by jamaljsr** [comment]
@aaronhayes yes, I am using a Mac. Thanks for the update. I'm going to close this since it cannot be resolved on our end.

**Comment by aaronhayes** [comment]
fair enough. I do believe mounting the unix socket as a volume would work on unix but have no way to check (as I'm also on Mac). 

CLN has a websocket connection coming in the next release, but that's for a seperate ticket ...
