### ISSUE TITLE
Feature Request: add LND connect URL for REST API.

### ISSUE THREAD

**Issue by ilyavf** [jamaljsr/polar#478]
**Is your feature request related to a problem? Please describe.**
LND connect Url contains parameters to work with GRPC API and not REST.

**Describe the solution you'd like**
Add a new field and a copy button for LND Connect REST API.

**Additional context**
![image](https://user-images.githubusercontent.com/1895948/127039604-efb0b43c-d74b-4eae-a0df-934744ac2490.png)

**Comment by WesleyCharlesBlake** [comment]
We need this !

**Comment by jamaljsr** [comment]
This should be pretty simple to implement. No objections from my end.

**Comment by bolatovumar** [comment]
What's the difference between the GRPC and REST `lndconnect` strings? Is it just the port? If not, can anyone point me to a resource which explains the difference? (I searched around but didn't find anything conclusive)
