### ISSUE TITLE
Feature Request: add CORS headers to REST API responses so that browser can talk to Polar.

### ISSUE THREAD

**Issue by ilyavf** [jamaljsr/polar#479]
**Is your feature request related to a problem? Please describe.**
Browser cannot directly talk to Polar via REST API due to the CORS issue.

**Describe the solution you'd like**
Send CORS headers with every response for REST requests:
```
access-control-allow-origin: *
```

**Additional context**
I am working on a web wallet, and it's very handy to use Polar for this. Also its pretty easy to explain to a non-tech how to use Polar. As of now I am running a proxy that simply adds the required header, but this is difficult for non-tech.

**Comment by eduardonunesp** [comment]
Would be awesome to have CORS headers like that

**Comment by wbobeirne** [comment]
Devils advocate here: Polar should behave as much like LND as possible, including its lack of CORS headers by default. However, LND did add CORS configuration last year, so maybe making it configurable in the UI could be nice? https://github.com/lightningnetwork/lnd/pull/4141.

I would suggest to anyone working on a web wallet though: Plan for not having CORS headers for most user's nodes REST APIs, as they're unlikely to have configured it.

**Comment by jamaljsr** [comment]
Thanks for the feedback all. I also feel like Polar should remain as close to the LND defaults as possible. I want to minimize features that automatically work in your dev environment but will require non-obvious manual configuration in production. This is why `keysend` and AMP are not enabled by default.

You can still get what you want by using Polar's [custom nodes](https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md) feature. Just click on "Manage Images", then "Add Custom Node".  

Fill out the form, with the custom LND config flags such as `--restcors=*`. You can use the same docker images that are built-in to Polar if all you want to customize are the flags. You also have the flexibility to use your own docker images if you want maximum customization.

![image](https://user-images.githubusercontent.com/1356600/127174367-74d9fe96-4f3e-4d24-a6e5-42053f3183fb.png)

Now you can use your custom CORS-enabled node in all your networks.

![image](https://user-images.githubusercontent.com/1356600/127176908-0a3c2706-5fa0-4ab7-a704-60e3b3bb90bf.png)

![image](https://user-images.githubusercontent.com/1356600/127174633-7c0baa31-4c47-4749-8bce-84cc9c4dd910.png)

I think this should solve the issue, but let me know if there are limitations I'm not aware of.
