### ISSUE TITLE
Bug: Stuck opening channels

### ISSUE THREAD

**Issue by noderunner11** [jamaljsr/polar#486]
**Describe the bug**
Created a new network of LNDs (0.13.1), deposited funds, mined blocks but the channels don't open. Tried to mine a few blocks because it said waiting for funding transaction to reach 3 confs but nothing happened after that too.

**To Reproduce**
1. Create a new network of multiple nodes
2. Deposit funds
3. Try opening channels
4. 2021-08-30 13:17:51.865 [INF] FNDG: Waiting for funding tx (bb90e6c4639ba5e6aad2925b1b3f3e7fdbfc41ec9b42460bfa13e34bf03e29cb) to reach 3 confirmations
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Expected behavior**
Channels should open

**Desktop (please complete the following information):**
- OS: [e.g. OSX Mojave or Windows 10 v1903]: MacOS Big Sur (Apple M1)
- Polar Version: [e.g. 0.2.0]: v1.3.0
- Docker Version: [e.g. 19.03.1]: v20.10.8
- Docker Compose Version: [e.g. 1.24.1] vv2.0.0-rc.1

**Comment by jamaljsr** [comment]
Yes, this ia a known issue with the M1 machines. You can work around it by rebuilding the docker images on your machine. See https://github.com/jamaljsr/polar/issues/442

**Comment by noderunner11** [comment]
> Yes, this ia a known issue with the M1 machines. You can work around it by rebuilding the docker images on your machine. See #442

Could you help me build the image? 
I am inside polar, I have to add a custom node? It's asking for a docker image, how do I get that?
I can git clone lnd in any folder and follow those instructions but how do I make polar pick up those?

**Comment by jamaljsr** [comment]
> Could you help me build the image?

There are instructions to build the image [here](https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md). 

> I am inside polar, I have to add a custom node? It's asking for a docker image, how do I get that?

Yes, you have to add a custom node. 

> I can git clone lnd in any folder and follow those instructions but how do I make polar pick up those?

Polar will automatically detect the docker images that were pulled or built on your machine and display them in the "Docker Image" field. You can also just type the name of the image, ex: `my-lnd-node:latest`

**Comment by noderunner11** [comment]
It worked! Thanks!

**Comment by jamaljsr** [comment]
👍

**Comment by ohenrik** [comment]
Should It not be possible to add M1 compatible nodes to Polar as standard for installations that run on M1 Macs?

**Comment by jamaljsr** [comment]
Yes, it is possible to make multi-arch Docker images that will be compatible for both Intel and M1 Macs. I currently do not have an M1 Mac to test on so wouldn't feel comfortable publishing images that I cannot confirm will actually function properly.
