### ISSUE TITLE
LND.conf for each node you create

### ISSUE THREAD

**Issue by noderunner11** [jamaljsr/polar#489]
Is there a way to set conf settings for each node you create? I see we can edit the image and start lnd with more flags but can we apply settings to each node separately?
I tried looking in the lnd folders of the nodes created but I did not find any individual conf file.

**Comment by jamaljsr** [comment]
Yes, you can edit the startup flags. Right-click on a node then click "Advanced Options". Click on the pre-fill icon (3 lines) to fill the default command. Customize the flags to your liking.

**Comment by noderunner11** [comment]
> Yes, you can edit the startup flags. Right-click on a node then click "Advanced Options". Click on the pre-fill icon (3 lines) to fill the default command. Customize the flags to your liking.

Thanks!
