### ISSUE TITLE
Bug: Unable to establish node network on Linux

### ISSUE THREAD

**Issue by secondl1ght** [jamaljsr/polar#500]
**Describe the bug**
I have Polar running on PopOS and the network started but all of the nodes within the network are in error state.

**To Reproduce**
1. Install Polar
2. Install Docker and Docker Compose
3. Run Polar as sudo
4. See network fail

**Expected behavior**
Networks starts and all nodes are active and connected.

**Screenshots**
![image](https://user-images.githubusercontent.com/85003930/136860925-83965323-841a-42c4-a4c1-788cdc59671d.png)

**Desktop (please complete the following information):**
- OS: Pop!_OS 21.04
- Polar Version: 1.3.0
- Docker Version: 20.10.9
- Docker Compose Version: 1.29.2

**Additional context**
Here are all of the error messages:

Alice:

Unable to connect to LND node
ENOENT: no such file or directory, open '/root/.polar/networks/1/volumes/lnd/alice/tls.cert'

Bob:

Unable to connect to c-lightning node
ENOENT: no such file or directory, open '/root/.polar/networks/1/volumes/c-lightning/bob/rest-api/access.macaroon'

Carol:

Unable to connect to eclair node
connect ECONNREFUSED 127.0.0.1:8283

Backend1:

Unable to connect to bitcoin node
connect ECONNREFUSED 127.0.0.1:18443

**Comment by jamaljsr** [comment]
Hey @secondl1ght it sounds like docker is not starting up the containers properly. 

Here are a few suggestions:
1. Right-click on the `backend1` node then click View Logs. Are there any errors logged?
2. I see you are running Polar as sudo. This shouldn't be necessary. Have you ran the post-install commands recommended by Docker (https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
3. See what happens if you try to start the nodes outside of Polar:
    1. Delete all your networks in Polar and close the app
    2. Open Polar without sudo
    3. Create a new network with 1 LND node and 1 Bitcoin node, but do not start it
    4. Close Polar
    5. Open a Terminal and run `docker-compose -f ~/.polar/networks/1/docker-compose.yml up`
    6. See if the nodes start or if any errors are logged

**Comment by secondl1ght** [comment]
Thanks for the suggestions

1. Nothing is showing in these logs just a spinning 'loading' icon
2. I set up the Docker as non-root user and launched Polar, however I have the same behavior as before where Docker is not detected on startup. (If I run as sudo it is detected).
3. I went through these steps while using sudo because I could not complete without sudo and after running the docker compose command in the terminal I received this error message: ```ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/home/mk/.polar/networks/1/docker-compose.yml'```

It looks like there is another option to run the docker daemon entirely rootless here: https://docs.docker.com/engine/security/rootless/

Maybe I could give that a try but the error message is something to do with the docker-compose.yml file not existing.

**Comment by secondl1ght** [comment]
Yes I ran ```docker run hell-world``` without sudo and it worked

Good call, I ran the docker-compose command as root and got the following error output:

```polar-n1-alice | loadConfig: Failed to create lnd directory: mkdir /home/lnd/.lnd/data: permission denied
polar-n1-alice | loadConfig: Failed to create lnd directory: mkdir /home/lnd/.lnd/data: permission denied
polar-n1-backend1 | 
polar-n1-backend1 | 
polar-n1-backend1 | ************************
polar-n1-backend1 | EXCEPTION: N5boost10filesystem16filesystem_errorE       
polar-n1-backend1 | boost::filesystem::create_directory: Permission denied: "/home/bitcoin/.bitcoin/regtest"       
polar-n1-backend1 | bitcoin in AppInit()       
polar-n1-backend1 | 
polar-n1-backend1 exited with code 1```

Does this give us more info? Looks like more permissions issues... I can test out the rootless docker daemon if needed, it's just a bit to get it setup.

**Comment by secondl1ght** [comment]
Unless I am missing something then it looks like I dont have the ```networks``` directory. 

My ```/root/.polar/``` directory only contains one directory named ```logs```.

**Comment by jamaljsr** [comment]
This is a bit of a mystery. The file had to exist to produce the file permission errors above. But ultimately, I was just trying to obtain more info. I think the workaround to run Polar as root is a dead end.

Let's focus on the "Docker Not Found" issue when running Polar as non-root as this is the use case that i've tested thoroughly and know should work. Can you run Polar, not as root, then check the logs in `~/.polar/logs/renderer.log`. 

What error is displayed after "fetching docker version"? This is what I see on my machine:
```
[2021-10-12 10:22:18.352] [debug] fetching docker version
[2021-10-12 10:22:18.419] [debug] Result: {"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"20.10.8","Details":{"ApiVersion":"1.41","Arch":"amd64","BuildTime":"2021-07-30T19:52:10.000000000+00:00","Experimental":"false","GitCommit":"75249d8","GoVersion":"go1.16.6","KernelVersion":"5.10.47-linuxkit","MinAPIVersion":"1.12","Os":"linux"}},{"Name":"containerd","Version":"1.4.9","Details":{"GitCommit":"e25210fe30a0a703442421b0f60afac609f950a3"}},{"Name":"runc","Version":"1.0.1","Details":{"GitCommit":"v1.0.1-0-g4144b63"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"20.10.8","ApiVersion":"1.41","MinAPIVersion":"1.12","GitCommit":"75249d8","GoVersion":"go1.16.6","Os":"linux","Arch":"amd64","KernelVersion":"5.10.47-linuxkit","BuildTime":"2021-07-30T19:52:10.000000000+00:00"}
[2021-10-12 10:22:18.422] [debug] getting docker-compose version
[2021-10-12 10:22:18.987] [debug] Result: {"exitCode":0,"err":"","out":"v2.0.0-rc.3\n","data":{"version":"v2.0.0-rc.3"}}
```

**Comment by jamaljsr** [comment]
Great, we're making progress! 🙌

Can you try these steps again now to see what the docker logs say?
1. Delete all your networks in Polar and close the app
1. Open Polar without sudo
1. Create a new network with 1 LND node and 1 Bitcoin node, but do not start it
1. Close Polar
1. Open a Terminal and run `docker-compose -f ~/.polar/networks/1/docker-compose.yml up`
1. See if the nodes start or if any errors are logged

**Comment by secondl1ght** [comment]
Ok awesome!

Here is the new output:

```Creating network "1_default" with the default driver
Creating polar-n1-backend1 ... done
Creating polar-n1-alice    ... done
Attaching to polar-n1-backend1, polar-n1-alice
polar-n1-alice | adding user lnd (1000:1000)
polar-n1-backend1 | adding user bitcoin (1000:1000)
polar-n1-backend1 | Running as bitcoin user: bitcoind -server=1 -regtest=1 -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
polar-n1-alice | Running as lnd user: lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice --tlsextradomain=alice --tlsextradomain=polar-n1-alice --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334 --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
polar-n1-alice | loadConfig: Failed to create lnd directory: mkdir /home/lnd/.lnd/data: permission denied
polar-n1-alice | loadConfig: Failed to create lnd directory: mkdir /home/lnd/.lnd/data: permission denied
polar-n1-backend1 | 
polar-n1-backend1 | 
polar-n1-backend1 | ************************
polar-n1-backend1 | EXCEPTION: N5boost10filesystem16filesystem_errorE       
polar-n1-backend1 | boost::filesystem::create_directory: Permission denied: "/home/bitcoin/.bitcoin/regtest"       
polar-n1-backend1 | bitcoin in AppInit()       
polar-n1-backend1 | 
polar-n1-backend1 exited with code 1
```

Seems to be exiting on a permissions issue again.

**Comment by jamaljsr** [comment]
It appears you still have some docker permission issues. The container cannot write to the volume mounted to your host OS. What are the permissions of the `~/.polar/networks/1/lnd/alice/` dir? Can you try deleting the whole `~/.polar` dir then reopen Polar. Maybe there were leftover files from previously running as root.

**Comment by jamaljsr** [comment]
Thats looks like a port conflict which is a different problem. You have another program listening on port 8081. You can either close that app or change the port number in the `docker-compose.yml` file. Polar does this automatically when it starts the network.

> If you have time I would be happy to do a screenshare so we can tackle this issue in real time. Might be quicker to get to the bottom of it.

Sure, DM me on Twitter or in the LND slack, im @jamaljsr on both

**Comment by secondl1ght** [comment]
Ok I closed the other app and tried again but got the same permissions issue, sending you a message now.

**Comment by akhilparakka** [comment]
Hi, Is there any update on this issue?
Thanks
