### ISSUE TITLE
Advice for developing with Polar

### ISSUE THREAD

**Issue by izz-j** [jamaljsr/polar#503]
Hey so I'm playing around with the default nodes (Alice, Bob, etc). I have a project on my host system that I would like to interact with the Alice Lightning node container. Basically, I'm trying to integrate lncli commands to manage payments for Alice node container from my host system. I'm doing this cause I don't want to run my entire project directory and editor (emacs) in a docker container. This is probably more of a docker question than polar, but nevertheless, I feel I could get good advice here.

**Comment by izz-j** [comment]
Sorry, yes I will rephrase. I have a project I am working on in my home directory (Debian). I want my code to interact with the polar nodes. How can I go about this?

Thank you again for your swift replies.

**Comment by jamaljsr** [comment]
Ah ok. Connecting your app to LND nodes in Polar depends on what programming language and application framework you are using. As a start, I would recommend taking a look at the sample app [walkthrough](https://docs.lightning.engineering/lapps/guides/polar-lapps) which is written in Typescript. There's also a companion [video](https://www.youtube.com/watch?v=6P0DZ74DmFA) that goes through this guide as well. 

In addition to that, I would also recommend taking a look at the [Resources](https://docs.lightning.engineering/community-resources/resource-list#developer-libraries-and-tools) page in the Builder's Guide. There are links to dev tools, libraries, as well as links to additional lists of resources.

Hope this helps.

**Comment by izz-j** [comment]
Ah ok thank you for these resources I will check them out! My project is written in Common Lisp, but I was am calling shell commands with it as well. So essentially I planned on calling `lncli` commands with lisp.

**Comment by jamaljsr** [comment]
Oh if you going to call `lncli` commands from your app, then you'll just need to use the flags I mentioned in https://github.com/jamaljsr/polar/issues/503#issuecomment-944016198 when executing the command. You will need to install `lnd` and `lncli` on your machine. You can just download the [binaries](https://github.com/lightningnetwork/lnd/releases) for your OS or [compile](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) from source.

**Comment by izz-j** [comment]
Yes exactly! Ok I see sorry for the confusion. I just grabbed those binaries! Thank you. How do I make the lnd binary use the bitcoin backened node in Polar? Cause when I run it, its looking for bitcoind.

**Comment by izz-j** [comment]
It seems when I run the command you mentioned. It just sends me to the help menu. But when I run `lncli` I get this:
`[lncli] could not load global options: could not load TLS cert file: open /home/izz/.lnd/tls.cert: no such file or directory`

To me it looks like the global setting still needs to be overridden. Cause by default `lncli` is looking for the cert in my home directory as soon as it runs. I copied alice's TLS cert to my home directory to appease it but then I get the same error but this time looking for the admin.macaroon file.  I'm thinking there must be a better way to get this to work..

**Comment by jamaljsr** [comment]
The command I sent is incomplete, it only includes the config arguments needed to connect to the Polar `lnd` node. You have to append the subcommand that you want to execute, for example `getinfo` or `listchannels`. You may also need to change the port or paths based on your local Polar network. View the Connect tab for the correct values.

**Comment by jamaljsr** [comment]
It's all good. Best of luck with your app.
