### ISSUE TITLE
Bug: LND fails to start after deleting TLS certs

### ISSUE THREAD

**Issue by jamaljsr** [jamaljsr/polar#508]
**Describe the bug**
If you start an LND node, then delete the TLS cert and key files, the node will fail to start again until Polar is restarted.

**To Reproduce**
1. Create new network with 1 bitcoind and 1 lnd node
1. Start the network
1. Open terminal for lnd node (alice)
1. `rm /home/lnd/.lnd/tls.*`
1. Restart `lnd` node (alice)

**Expected behavior**
The node starts successfully

**Desktop (please complete the following information):**
- OS: OSX Bug Sur
- Polar Version: v1.3.0
- Docker Version:  v20.10.8
- Docker Compose Version: v1.29.2

**Additional context**
This issue was reported by a user in the LND Slack.

**Comment by setpill** [comment]
Workaround:

> if you restart polar in between restarting alice then it will turn green

**Comment by amovfx** [comment]
Damn, I'm having the same problem. :(
