### ISSUE TITLE
Docker Image fails to build for M1 Mac

### ISSUE THREAD

**Issue by niteshbalusu11** [jamaljsr/polar#513]
**Describe the bug**
Docker Image fails to build for M1 mac using these instructions: 
https://github.com/jamaljsr/polar/blob/master/docs/custom-nodes.md

It fails with the following errors.

```
#8 8.925 go: errors parsing go.mod:
#8 8.925 /go/src/github.com/lightningnetwork/lnd/go.mod:104: unknown directive: retract
#8 8.932 \033[0;32m Building debug lnd and lncli.\033[0m
#8 8.932 GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=v0.14.0-beta -X github.com/lightningnetwork/lnd/build.CommitHash=df0b82f0165f19bde8832bacd1e35544b0a2990d -X github.com/lightningnetwork/lnd/build.GoVersion=go1.13.15 -X github.com/lightningnetwork/lnd/build.RawTags=dev" github.com/lightningnetwork/lnd/cmd/lnd
#8 8.944 go: errors parsing go.mod:
#8 8.944 /go/src/github.com/lightningnetwork/lnd/go.mod:104: unknown directive: retract
#8 8.945 make: *** [Makefile:135: build] Error 1
------
executor failed running [/bin/sh -c apk add --no-cache --update alpine-sdk     git     make     gcc &&  git clone https://github.com/lightningnetwork/lnd /go/src/github.com/lightningnetwork/lnd &&  cd /go/src/github.com/lightningnetwork/lnd &&  git checkout $checkout &&  make &&  make install tags="signrpc walletrpc chainrpc invoicesrpc routerrpc"]: exit code: 2
```

**Comment by niteshbalusu11** [comment]
I even tried building from source and changing the docker file for lnd and rebuilding the app but the build fails. Both `yarn dev` and `yarn package` fails with this error.

```
[dev:app] node:internal/modules/cjs/loader:488
[dev:app]       throw e;
[dev:app]       ^
[dev:app] 
[dev:app] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/nitesh/Downloads/utils/polar/node_modules/postcss-safe-parser/node_modules/postcss/package.json
[dev:app]     at new NodeError (node:internal/errors:371:5)
[dev:app]     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
[dev:app]     at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
[dev:app]     at resolveExports (node:internal/modules/cjs/loader:482:36)
[dev:app]     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
[dev:app]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
[dev:app]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[dev:app]     at Module.require (node:internal/modules/cjs/loader:999:19)
[dev:app]     at require (node:internal/modules/cjs/helpers:102:18)
[dev:app]     at Object.<anonymous> (/Users/nitesh/Downloads/utils/polar/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
[dev:app]   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
[dev:app] }
[dev:app] 
[dev:app] Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[dev:app] yarn run dev:app exited with code 1
--> Sending SIGTERM to other processes..
[dev:electron] yarn run dev:electron exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by niteshbalusu11** [comment]
Ok, update on the docker image building. 

Had to change the Docker file to `ARG checkout="v0.13.1-beta"` instead of ARG checkout="master"

and changed the build command to `docker build --tag=m1mac/lnd --build-arg checkout=v0.13.1-beta .`

Can you please add support for lnd0.14.0 and also help me as to why the app isn't building from source using yarn?

**Comment by jamaljsr** [comment]
Hey @niteshbalusu11, I finally have an M1 machine and I'm planning on working on updating the images over the weekend.

**Comment by niteshbalusu11** [comment]
> Hey @niteshbalusu11, I finally have an M1 machine and I'm planning on working on updating the images over the weekend.

Awesome, thanks!

**Comment by niteshbalusu11** [comment]
Ok, I was able to build master and 0.14.0-beta images as well.
Change needed was `FROM golang:1.17.3-alpine as builder` in the Dockerfile.

**Comment by lucas-naman** [comment]
Hi @niteshbalusu11,

Did you find a way to make the bitcoind node work as well ?

Here is my error :

```
polar-n1-backend1
polarlightning/bitcoind:0.21.1
EXITED (255)
adding user bitcoin (1000:1000)

Running as bitcoin user: bitcoind -server=1 -regtest=1 -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

**Comment by niteshbalusu11** [comment]
> Hi @niteshbalusu11,
> 
> Did you find a way to make the bitcoind node work as well ?
> 
> Here is my error :
> 
> ```
> polar-n1-backend1
> polarlightning/bitcoind:0.21.1
> EXITED (255)
> adding user bitcoin (1000:1000)
> 
> Running as bitcoin user: bitcoind -server=1 -regtest=1 -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
> 
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> ```

Hey @lucas-naman 

https://github.com/ruimarinho/docker-bitcoin-core

I used image from here and inside polar, I changed the start flags, used polar’s start flags and it works fine.

**Comment by jamaljsr** [comment]
@lucas-naman make sure that the bitcoind Dockerfile is updated to download the ARM binaries, not the x64 ones.

I spent some time working on this over the weekend, but didn't complete it. I ran into that same error and now need to automate architecture detection for the Dockerfiles to download the correct binaries for each node implementation. I'm hoping to finish it up in the next day or two.

**Comment by lucas-naman** [comment]
Thank you @niteshbalusu11 and @jamaljsr for your answers.
I will try your suggestions as soon as possible.

@jamaljsr the automatic detection sounds amazing. Just like polar.

**Comment by niteshbalusu11** [comment]
> Hey @niteshbalusu11, I finally have an M1 machine and I'm planning on working on updating the images over the weekend.

Hey - Looks like there is no easy straight forward way to dynamically set the lnd architecture in the download path, seems like a weird docker limitation. Not sure if you found something to get around that, if not can you release images that build lnd from source to get around this problem? Guess they just a take little longer to build.

**Comment by jamaljsr** [comment]
FYI: I have pushed new multi-arch images for Bitcoin Core v22.0 and LND v0.14.1-beta. These should work on M1 machines without any issues. Please check for the latest node updates to use those images in Polar. Let me know if there are any issues.

**Comment by niteshbalusu11** [comment]
Closing this issue, the new images work good.
