### ISSUE TITLE
Feature Request: Update LND versions

### ISSUE THREAD

**Issue by michaelWuensch** [jamaljsr/polar#515]
**Is your feature request related to a problem? Please describe.**
I have clicked the "check for new node versions"
The latest LND version seems to be 0.13.1
Since then 5 new versions have been released.

**Describe the solution you'd like**
Ability to add a LND 0.14.1-beta node

**Comment by jamaljsr** [comment]
I have started working on this and should have it ready this week.

**Comment by sako0938** [comment]
Awesome this would be a great thing, waiting for the LND 0.14.1 release for Polar

**Comment by jamaljsr** [comment]
Resolved by #519
