### ISSUE TITLE
Bug: no_route to node after node is manually stopped and started again

### ISSUE THREAD

**Issue by grunch** [jamaljsr/polar#516]
I am not sure if this is a problem of polar or LND, I will try here first, I have a network with 3 LND nodes, Alice, Bob and Carol, all of them have channels and are balanced, they can send money to each other any time without problem, but if I shutdown carol and started it again she is now unable to receive payments, I just receive a `no_route` error message.

**Expected behavior**
All nodes should be able to receive even if the were restarted.

**Desktop:**
- OS: Linux 5.13.0-21-generic # 21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Polar Version: 1.3.0
- Docker Version: 20.10.11
- Docker Compose Version: 1.27.4

Here the log from the sender:
```
2021-11-28 16:58:53.625 [WRN] RPCS: Unable to send payment: no_route
2021-11-28 16:59:16.396 [WRN] CRTR: Failed to find route for payment c5937f94bc7d213c2672e35c237c3d311b9107dfd565035bba9faa8e3a5e2de9: unable to find a path to destination
```

Any ideas?

**Comment by jamaljsr** [comment]
I've run into this plenty of times myself and usually waiting 5-10 minutes will resolve it. I believe it has something to do with the channel status flipping between active and inactive, but I'm not 100% sure of the exact reason. Does it work for you after waiting some time?

**Comment by grunch** [comment]
yeah it works for me, thanks for the response, closing it
