### ISSUE TITLE
Bug: Docker containers not shutting down when closing GUI

### ISSUE THREAD

**Issue by secondl1ght** [jamaljsr/polar#521]
**Describe the bug**
When exiting out of the application and then running `docker ps` it looks like the docker containers do not shut down and continue running after the GUI has been closed.

**To Reproduce**
1. Run Polar and launch a network
2. Close out of the GUI
3. Check docker containers in terminal

**Expected behavior**
Docker containers get shutdown when GUI is closed.

**Desktop (please complete the following information):**
- OS: PopOS
- Polar Version: v1.3.0
- Docker Version: 20.10.11
- Docker Compose Version: 1.29.2

**Additional context**
If I have missed something please let me know.

**Comment by jamaljsr** [comment]
Thanks for the feedback. This has indeed been an annoyance to me every once in a while.

**Comment by Abdulkbk** [comment]
I will work on this @jamaljsr

**Comment by jamaljsr** [comment]
Sounds good. Thank you!

**Comment by Abdulkbk** [comment]
HI @jamaljsr, I am having a blocker. 

I worked on a solution for this issue but I noticed that the test failed. 

My implementation involves leveraging electron's 'before-quit' when a user exits polar and sending a message to the renderer process from main process. Now the blocker I have is that I imported `ipcRenderer` from electron in a react component and I used it to listen to messages from the main process. This works fine during development but a test always fails.

I tried a couple of solutions I found online including adding a preload.js script and exposing ipcRenderer through contextBridge. None seems to be working.

So I would appreciate it if you could advise me on how I can access ipcRendrer or point me to resources. I  think that would really help.

**Comment by Abdulkbk** [comment]
HI @jamaljsr, I am having a blocker. 

I worked on a solution for this issue but I noticed that the test failed. 

My implementation involves leveraging electron's 'before-quit' when a user exits polar and sending a message to the renderer process from main process. Now the blocker I have is that I imported `ipcRenderer` from electron in a react component and I used it to listen to messages from the main process. This works fine during development but a test always fails.

I tried a couple of solutions I found online including adding a preload.js script and exposing ipcRenderer through contextBridge. None seems to be working.

So I would appreciate it if you could advise me on how I can access ipcRendrer or point me to resources. I  think that would help.

**Comment by jamaljsr** [comment]
Hey @Abdulkbk, have you tried mocking the `ipcRenderer`'s methods using `jest.fn()`? I've done this before in the [ipcService tests](https://github.com/jamaljsr/polar/blob/master/src/lib/ipc/ipcService.spec.ts#L6). 

Another approach that may work is to use `jest.mock('electron');` to mock the entire library, but this way requires filling in more of the exposed API. 

Something like this:
```
jest.mock('electron', () => ({
  ipcRenderer: {
    on: jest.fn(),
    removeAllListeners: jest.fn(),
  },
}));
```

**Comment by Abdulkbk** [comment]
> Hey @Abdulkbk, have you tried mocking the `ipcRenderer`'s methods using `jest.fn()`? I've done this before in the [ipcService tests](https://github.com/jamaljsr/polar/blob/master/src/lib/ipc/ipcService.spec.ts#L6).
> 
> Another approach that may work is to use `jest.mock('electron');` to mock the entire library, but this way requires filling in more of the exposed API.
> 
> Something like this:
> 
> ```
> jest.mock('electron', () => ({
>   ipcRenderer: {
>     on: jest.fn(),
>     removeAllListeners: jest.fn(),
>   },
> }));
> ```

Alright. I would mock `ipcRenderer`'s method and see if the test will pass.

**Comment by Abdulkbk** [comment]
I mocked ipcRenderer and it worked @jamaljsr.

I've submitted a PR. I'll wait for your review and feedback. Thank you
