### ISSUE TITLE
Feature Request: Mine/send bitcoin to address

### ISSUE THREAD

**Issue by kornpow** [jamaljsr/polar#523]
**Is your feature request related to a problem? Please describe.**
I would like to use an external on-chain wallet for interacting with the regtest bitcoin network. Currently I have to go the shell and send a transaction an address generated in my external wallet software.

**Describe the solution you'd like**
I would like a "Mine to address" textbox in each bitcoin node, which allows me to easily fund one of these external wallet.

An alternative, and probably easier solution would be a "send to address" textbox.

Though I admit, while testing this, I was able to deposit funds, using the polar GUI, to the LND node, then send using the LND node to my external wallet. But I could see the process being easier.

**Comment by jamaljsr** [comment]
Thanks for the suggestion. I agree that it would be nice to have a simple "Send to Address" field for the Bitcoin node. This is something that isn't very difficult to add.

**Comment by khushbooag4** [comment]
Can I work on this issue.

**Comment by jamaljsr** [comment]
It's all yours! Go for it 👍

**Comment by Extheoisah** [comment]
Hi @jamaljsr  @khushbooag4 I'd like to know if this issue has or is currently been worked on?

**Comment by Extheoisah** [comment]
@jamaljsr Alright. I'm just getting used to Polar. I'd take this up and see what I can do
