### ISSUE TITLE
How do I fully uninstall Polar from my Mac?

### ISSUE THREAD

**Issue by suhailsaqan** [jamaljsr/polar#524]
I am trying to uninstall Polar from my Mac. 

I am having problems with deleting nodes, it keeps erroring out. Therefore I want to remove the whole software and reinstall it again.

When I tried uninstalling it, the nodes come back after I reinstall it. How do I remove everything?

**Comment by jamaljsr** [comment]
Hey, to remove all of Polar's files that are stored on your Mac, you can run the following commands

```
rm -rf /Applications/Polar.app
rm -rf ~/Library/Application\ Support/polar/
rm -rf ~/.polar
```

You'll also want to remove all docker images that were downloaded by Polar.

```
docker rmi -f $(docker images --filter=reference="polarlightning/*" -q)
```
