### ISSUE TITLE
Bug: Eclair node fails to start on M1 Mac

### ISSUE THREAD

**Issue by deregs** [jamaljsr/polar#532]
Has anyone gotten an Eclair node to work reliably on an M1 mac? LND works fine with the new arm image, and c-lightning works for some reason even without the arm image, but Eclair is hit or miss. I noticed that I can sometimes get Eclair to work when I start up an Eclair node, it fails to start, and then I start it again. Although even when I get it to start, opening channels to other nodes fails.

**Comment by jamaljsr** [comment]
Yes, I have gotten bitcoind and lnd working on M1 Macs because they provide arm64 pre-built binaries. Eclair and c-lightning require compiling from source code and I havent figured out how to get multi-arch docker images built for them so far. I will revisit it soon now that I know someone is interested in seeing it implemented.

**Comment by NonsoAmadi10** [comment]
Hello @jamaljsr I know how to build multi-arch docker images. Is it okay if you give me enough context on how I can contribute. I would love to tackle this issue

**Comment by NonsoAmadi10** [comment]
I just saw the commits. I can finish it for you, I can write the docker file arm64 for eclair. Would this be something you love me to do? If yes, I would have a PR by monday. Also I would love to know how I can contribute, do I check into your branch after forking and checkout from there and continue?

**Comment by jamaljsr** [comment]
Yes, I'd appreciate the contribution if you'd like to help.

> Also I would love to know how I can contribute, do I check into your branch after forking and checkout from there and continue?

You can just fork the repo, create your own branch, then copy the incomplete changes from my branch. Once you're done, you can open a PR.

> I also noticed you are using a slim buster base image which is quite different from how the original eclair amd64 docker file uses, is there a particular reason why polar chose this? Was the docker image size a factor that was considered?

The [Dockerfile](https://github.com/ACINQ/eclair/blob/v0.8.0/Dockerfile) I used is just a modified of the [Dockerfile](https://github.com/ACINQ/eclair/blob/v0.8.0/Dockerfile) from the Eclair repo. I typically will update this to match with each new release. Where exactly are you seeing a difference?
