### ISSUE TITLE
Feature Request: Always show "Check for new Node Versions"

### ISSUE THREAD

**Issue by jonafll** [jamaljsr/polar#542]
**Is your feature request related to a problem? Please describe.**
The link for "check for new Node Versions" is only visible when "Show all Versions" is active. Then you have to scroll all the way down to find the link. This is especially annoying on small screens. Also, the link is hard to find that way, especially if you don't even know it exists.

**Describe the solution you'd like**
Maybe we can check for new versions on startup. In Addition we can always show the link even if "Show all versions" isn't checked.

**Comment by jamaljsr** [comment]
Thanks for creating this issue. I agree 100% with relocating the "Check for new Node Version" link. It is currently buried behind too many clicks.

Checking for new versions on startup would be cool if we can make it opt-in. Maybe on the initial "Let's Get Started" screen, there can be a checkbox to allow the user to enable automatic checks.

**Comment by jonafll** [comment]
Since there is no "global" settings menu, I think this is a good idea. I would also suggest adding this option to the Image Updates Modal, because once the user has created a network, they can't disable this option later unless they remove all their networks to show the initial "Let's Get Started" screen.

**Comment by jamaljsr** [comment]
Yeah, that's a good point. Agreed
