### ISSUE TITLE
My Mac says -“Polar” cannot be opened because the developer cannot be verified.-

### ISSUE THREAD

**Issue by RenSylvain** [jamaljsr/polar#544]
Anybody know how to fix this?

**Comment by RenSylvain** [comment]
Solved. Google result is as follows: 

If you go to System Preferences > Security & Privacy and click on the General tab, you will see only two options for Allow apps downloaded from: App Store or App Store and identified developers.

**Comment by jamaljsr** [comment]
Hey, thanks for the feedback. Yes, this is typical for Mac apps that do not sign the build with developer certificates. I've intentionally chosen not to do this for now because of the pretty big hassle for a minor benefit. I may revisit in the future if a more pressing need arises.
