### ISSUE TITLE
Bug: bitcoind running on wrong port

### ISSUE THREAD

**Issue by ErikEk** [jamaljsr/polar#552]
When I go into Action->Edit option (for any bitcoind instance), the config zmqpubrawtx parameter is set to tcp://0.0.0.0:28335, but under the Connect tab is shows that it run on tcp://127.0.0.1:29335. These were the default settings.
It seems like bitcoind is running on tcp://127.0.0.1:29335 when I try to connect to it.

**Comment by jamaljsr** [comment]
Yes, this is how Docker internal networks are intended to work. 

`0.0.0.0:28335` is the value passed to bitcoind to instruct it to listen on all interfaces on port `28335`. With this alone, you would not be able to connect to bitcoind from your host machine. 

`28335:29335` is specified in the `docker-compose.yml` file for the network which maps port `28335` on the bitcoind node to port `29335` on your host machine. 

When you connect from your machine to `127.0.0.1:29335`, Docker will forward the request to the bitcoind node running on port `28335`. 

The port `29335` is chosen dynamically by Polar when the network is starting. It will detect which ports on your machine are available and assign them to the different bitcoin/LN nodes based on what is available. Try adding multiple bitcoind nodes then start the network to see how the ports are unique.

I hope this helps clear things up. If you've found something that isn't working as expected, please feel free to respond.

**Comment by ErikEk** [comment]
@jamaljsr Thank you.
