### ISSUE TITLE
Feature Request: Support Core Lightning v0.11.0 with gRPC interface

### ISSUE THREAD

**Issue by fusion44** [jamaljsr/polar#556]
**Is your feature request related to a problem? Please describe.**
Since v0.11.0 Core Lightning has a gRPC API similar to LND. Exposing this API would be a great addition.

**Describe the solution you'd like**
Expose this API. To start lightningd with gRPC support, pass the argument `grpc-port`. E.g. `lightningd --signet --grpc-port=9537`
CLN will create three files which must be available to clients:
* `.lightning/signet/client.pem`
* `.lightning/signet/client-key.pem`
* `.lightning/signet/ca.pem`

The connection details could be exposed via the UI, similar to how LND is handled.

**Comment by jamaljsr** [comment]
I'll get this added soon. Thanks for the additional details on the GRPC certs.
