### ISSUE TITLE
Bug: Unable to connect to node

### ISSUE THREAD

**Issue by oldeucryptoboi** [jamaljsr/polar#557]
**Describe the bug**
No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)

**To Reproduce**
Just start Polar from scratch

**Expected behavior**
Working

**Additional context**
How do I set up a wallet in the docker image that has been downloaded by Polar?

What is the command I should add to dockercompose to setup a wallet and avoid this error?

**Comment by jamaljsr** [comment]
I haven't seen this issue before. The bitcoind wallet should be automatically created for you when you start the network. Are you trying to run the network via the `docker-compose` CLI?

**Comment by ConorOkus** [comment]
Not since core 21 or 22. You get this error message. Core no longer loads a wallet by default...

```No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)```

**Comment by jamaljsr** [comment]
Are you facing this issue too @ConorOkus? 

Polar already [creates a default wallet](https://github.com/jamaljsr/polar/blob/master/src/lib/bitcoin/bitcoindService.ts#L28) if one doesn't already exist, during the [network startup](https://github.com/jamaljsr/polar/blob/master/src/store/models/network.ts#L626) process. This is why I asked @oldeucryptoboi if he was trying to start the network outside of Polar, using just `docker-compose`. This would explain why he's facing this problem.

**Comment by ConorOkus** [comment]
Yes I've faced this issue before as well, core doesn't do this by default anymore.

**Comment by jamaljsr** [comment]
Can either of you provide any additional details on how & when you run into this issue. I've been trying but am unable to reproduce the problem myself.

**Comment by jamaljsr** [comment]
Closing this out due to inactivity.
