### ISSUE TITLE
Feature Request: Automatic mining every X minutes

### ISSUE THREAD

**Issue by Jossec101** [jamaljsr/polar#566]
Hi there! Awesome tool :) 

**Is your feature request related to a problem? Please describe.**
Sometimes we want to mimick a bitcoin blockchain mining time 
**Describe the solution you'd like**
A button in the UI with one setting to tell bitcoind to generate a block every N minutes

BR,

**Comment by jamaljsr** [comment]
Agreed, this would be a great addition to add. Thanks for the feedback.

**Comment by Jhoyola** [comment]
I started doing this. Will look something like this.

![screenshot_polar_automine](https://user-images.githubusercontent.com/42843554/233441755-c2c422fc-5159-4540-b9d7-0d49cc8848d2.png)

**Comment by jamaljsr** [comment]
FYI: Someone else started working on this feature a while back in https://github.com/jamaljsr/polar/pull/613. It was close to being done. I planned to finish where they left off when time permitted. It may be helpful to view my feedback there to inform your approach.

**Comment by Jhoyola** [comment]
Maybe I could actually finish their code, as it's further than mine and he even made the nice progressbar.

**Comment by jamaljsr** [comment]
Sounds good to me
