### ISSUE TITLE
Bug: Can't create a new Lightning network

### ISSUE THREAD

**Issue by danielgranhao** [jamaljsr/polar#569]
**Describe the bug**
When I try to create a new Lightning network, I input a network name and how many managed nodes I want, but nothing happens when I press _Create Network_. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the _Create Network_ dialog
2. Input a network name
3. Press the _Create Network_ button
4. Nothing happens

**Expected behaviour**
A network should be created

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.4
- Polar Version: 1.3.0
- Docker Version: 20.10.14
- Docker Compose Version: 1.29.2

**Additional context**
This worked before, and the networks I already have work as expected. 
I've already tried restarting polar, restarting docker and also removing the executable and installing a new one.

**Comment by jamaljsr** [comment]
Apologies for the delayed response, I'm traveling at the moment.

To troubleshoot this, can you take a look at the log files in `~/.polar/logs/`? It would be easier to delete the files first, then reproduce the bug, then read the logs. You can share them in this issue as well, there isn't any personal info in them.

**Comment by danielgranhao** [comment]
Thanks for the help! Here are my log files:
[renderer.log](https://drive.google.com/file/d/1dO2wp8VbIyy0CCepbWpZCnoz0XrFlCtY/view?usp=sharing)
[main.log](https://drive.google.com/file/d/1PVKpWmesiCg-mwqn0rt6BW0IOe-hNRdL/view?usp=sharing)

**Comment by jamaljsr** [comment]
The logs you shared do not show that you attempted to create a new network. Can you repeat your steps to get to where you click on the "Create Network" button and nothing happens, then share the logs after that point.

**Comment by danielgranhao** [comment]
These are the logs after I pressed "Create Network". I've just tried again and even pressed the button a bunch of times, but the logs don't change when I do so 🤔

**Comment by jamaljsr** [comment]
I created #580 which will help diagnose why the network is not being created for you. Are you able to test this branch by running Polar in `dev` mode? If not, no worries. We'll just need to wait until I package up a new release to gather more info.

**Comment by danielgranhao** [comment]
Thanks! When I run it, the issue is gone... 😲 if I open the old version again, the issue is still there. I will just use the most recent version 🙂 I'm curious what the issue was but don't know to diagnose

**Comment by jamaljsr** [comment]
Cool. Thanks for trying it. I'm surprised that it works as well, but glad you're able to use Polar again.
