### ISSUE TITLE
Bug: Bot broke master while auto-updating dependencies

### ISSUE THREAD

**Issue by ktecho** [jamaljsr/polar#574]
**Describe the bug**

A failure message appears when you try to open a channel from one LN node to another (see screenshot below).

It worked yesterday, but it doesn't today:

In this commit, master breaks: https://github.com/jamaljsr/polar/commit/67be04ba073daa88ad64c9d7b82891cf7dbc7d92

I've tried checking out the previous commit and it works flawlessly, so I think that's the problem.

I could send a PR reversing the commit, but I don't know how that bot works. Is he going to update the dependency again maybe?

**To Reproduce**
1. Clone "master"
2. execute `yarn` and `yarn package`
3. Run polar using AppImage
4. Create a network with default values
5. Create an outbound channel from the first node to the second one
6. You'll get the error message from the screenshot below

**Expected behavior**
You, being able to open the channel :)

**Screenshots**
![image](https://user-images.githubusercontent.com/547169/180574416-1849d237-ec81-48d1-82dd-67df7fb90271.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- Polar Version: master

**Comment by jamaljsr** [comment]
Sometimes the automatic dependency updates break things at runtime even though all of the tests past. It likely just requires a small code change to become compatible with the new `bitcoin-core` version. I'll take a look next week.

**Comment by ktecho** [comment]
This needs more testing, but the bot updated `bitcoin-core` to v4.1 and he upgraded some other dependencies too and `master` seems to work fine.

I'll report back when I do some more testing.

**Comment by jamaljsr** [comment]
Cool. I haven't gotten a chance to test `master` yet, but will do it soon to see if I run into any issues.

**Comment by jamaljsr** [comment]
I tested `master` and was unable to reproduce this issue on my machine. I'm running on a Mac, so maybe the issue is only present on Linux. Please let me know if you gather any additional info or are able to reliably reproduce this.

**Comment by ktecho** [comment]
Nah, I'm closing it, as I've been working with `master` since then a few times and it's working fine now. Thanks!
