### ISSUE TITLE
Bug: Insufficient balance when paying an invoice? 

### ISSUE THREAD

**Issue by mariogintili** [jamaljsr/polar#582]
**Describe the bug**

Hello everyone!

It looks like I can't get an invoice paid even though the account at hand has more than enough to pay

![polar-broken-demo](https://user-images.githubusercontent.com/3522106/184176299-a172d8b5-fdf5-48bc-90dc-fc835071617a.gif)

**To Reproduce**

- Download the latest version of polar for mac
- Create a test network
- Have 2 accounts with +1M sats
- Issue an invoice for 1 sat
- Attempt to pay
- See `insufficient_balance` error

**Expected behavior**

I would expect the invoice to be paid

**Screenshots**

added above

**Desktop (please complete the following information):**
- OS: MacOS Monterey 1.2
- Polar Version: 1.3.0
- Docker Version: 4.11.1
- Docker Compose Version: 1.29.2

**Additional context**

**Comment by jamaljsr** [comment]
The balance you see there is the on-chain wallet, not the balance on lightning. It looks like you havent created any channels yet. You have to open channels between the nodes in order to make a payment between them.

Check out the video on https://lightningpolar.com to see a walkthrough of opening channels and making a payment.

**Comment by mariogintili** [comment]
thanks @jamaljsr 😄 I will check it out and comment back here. When I solve it I'll close the issue. I think a few people new to blockchain development will find this conversation helpful

**Comment by mariogintili** [comment]
@jamaljsr setting up the channel was the issue, thank you very much!

On the other hand, the slack invite seems expired on the official website, how could I have an invite please? I am developing a lighting app and I'm struggling to find community support in general

**Comment by jamaljsr** [comment]
Where is the broken Slack invite link? I'd like to fix it.

Unfortunately, the invite links provided by Slack have an expiration on them. You should always be able to find the working link on the https://lightning.engineering/ website.

**Comment by mariogintili** [comment]
@jamaljsr 

![broken-slack-link](https://user-images.githubusercontent.com/3522106/184533093-ac840a1e-e420-46b9-ac56-7ad40e053d14.gif)

**Comment by jamaljsr** [comment]
Thanks for the heads up. We'e updated the invite link. It works now.
