### ISSUE TITLE
Feature Request: support colima docker runtimes

### ISSUE THREAD

**Issue by count-null** [jamaljsr/polar#595]
**Is your feature request related to a problem? Please describe.**
On macOS I prefer not to use docker desktop. It's not FOSS and I don't need another desktop app open when developing. I use https://github.com/abiosoft/colima as a docker runtime with docker and docker-compose installed with brew.

Polar does not detect the docker version and insists I install docker desktop, meanwhile I can use docker just fine in command line. 

**Describe the solution you'd like**
Polar should detect the docker version and be able to use the docker runtime in colima for mac users.

**Comment by jamaljsr** [comment]
This is the first I am hearing of the `colima` project so I am not sure how it works. Polar uses the [dockerode](https://www.npmjs.com/package/dockerode) NPM package to detect and communicate with Docker. It can use these methods to detect the Docker installation on the host machine. 

```js
var Docker = require('dockerode');
var docker = new Docker({socketPath: '/var/run/docker.sock'});
var docker1 = new Docker(); //defaults to above if env variables are not used
var docker2 = new Docker({host: 'http://192.168.1.10', port: 3000});
var docker3 = new Docker({protocol:'http', host: '127.0.0.1', port: 3000});
var docker4 = new Docker({host: '127.0.0.1', port: 3000}); //defaults to http
```

Does `colima` expose one of these interfaces that Polar could use to communicate with it?

**Comment by count-null** [comment]
Looks like colima puts the socket in a custom location: `$HOME/.colima/default/docker.sock`

https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#docker-socket-location

**Comment by count-null** [comment]
Seems like #482 would allow colima runtimes to work if solved

**Comment by count-null** [comment]
I was able to hack it by creating a simlink to the expected sock location
`ln -s $HOME/.colima/default/docker.sock /var/run/docker.sock`

**Comment by count-null** [comment]
Closing as duplicate

**Comment by jamaljsr** [comment]
Thanks for the updates. Glad that you were able to find a workaround for now.

> Seems like #482 would allow colima runtimes to work if solved

Agreed. Resolving this bug would likely fix this issue as well without needing the workaround.
