### ISSUE TITLE
Bug: Transaction isn't being mind

### ISSUE THREAD

**Issue by Ashleyhen** [jamaljsr/polar#596]
![image](https://user-images.githubusercontent.com/84979436/189515170-7c191d5f-392d-4194-98a8-dd31cc3daccf.png)

Txid: c0fb19d5f93d58306f728bf36c1b8cefc2048f9c11370aa8793d5600905a70f6

![image](https://user-images.githubusercontent.com/84979436/189515277-34e34565-1a60-45c3-b52c-8ab42b0edd66.png)

![image](https://user-images.githubusercontent.com/84979436/189515293-630c73ec-e107-4367-ae9f-a9ffc2b5e0c5.png)

For some reason when you review the transaction the amount shows up as negative, then when you try to list the unspent transactions with respect to the address there doesn't appear to be any unspent utxo's associated with that address 

help

**Comment by jamaljsr** [comment]
Hey @Ashleyhen, which node wallet did you use to create the destination address that ends in `pxl6`?

**Comment by Ashleyhen** [comment]
> Hey @Ashleyhen, which node wallet did you use to create the destination address that ends in `pxl6`?

I used rust to generate a tr address

**Comment by jamaljsr** [comment]
I am not fully understanding your setup. Is your Rust app using the `backend1` node's RPC API to create the destination address, or is it managing the wallet & private keys itself?

The reason I ask is because the `listunspent` command would only show the `pxl6` UTXO if  `backend1` was used to create the address. If the address (and private key) was created by your Rust app, then the 10 coins are now owned by your app and not the `backend1` node. This would explain why it is not showing the unspent UTXO in the `listunspent` response.

**Comment by Ashleyhen** [comment]
> 

The rust app generates the private keys however, I thought if including the script the unspent transaction would be the transactions associated with that address s 
 bitcoin-cli listunspent 6 9999999 "[\"bcrt1pp375ce9lvxs8l9rlsl78u4szhqa7za748dfhtjj5ht05lufu4dwsshpxl6\"]"

**Comment by Ashleyhen** [comment]
> I am not fully understanding your setup. Is your Rust app using the `backend1` node's RPC API to create the destination address, or is it managing the wallet & private keys itself?
> 
> The reason I ask is because the `listunspent` command would only show the `pxl6` UTXO if `backend1` was used to create the address. If the address (and private key) was created by your Rust app, then the 10 coins are now owned by your app and not the `backend1` node. This would explain why it is not showing the unspent UTXO in the `listunspent` response.
> 

The rust app generates the private keys however, I thought if including the script the unspent transaction would be the transactions associated with that address 
 bitcoin-cli listunspent 6 9999999 "[\"bcrt1pp375ce9lvxs8l9rlsl78u4szhqa7za748dfhtjj5ht05lufu4dwsshpxl6\"]"

**Comment by jamaljsr** [comment]
From my understanding, `listunspent` will only display the unspent UTXOs that the `bitcoind` node is capable of spending from its internal wallet, which means it would have the private keys.

I think this is more of a Bitcoin Core question and not really an issue with Polar itself. I'm sure you'd be able to get a definitive answer by asking on the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/).

**Comment by Ashleyhen** [comment]
I found the problem for some reason you have to tell bitcoin-cli to scan for externally generated addresses 
with "importmulti" for example:

bitcoin-cli importmulti '[{"scriptPubKey": {"address": "bcrt1pp375ce9lvxs8l9rlsl78u4szhqa7za748dfhtjj5ht05lufu4dwsshpxl6"},"timestamp":1662835676}]' '{"rescan":true}'

**Comment by jamaljsr** [comment]
Thanks for the update. I'm glad you were able to find the solution.
