### ISSUE TITLE
Bug: cannot get core-lightning image to build

### ISSUE THREAD

**Issue by niteshbalusu11** [jamaljsr/polar#602]
**Describe the bug**

I am unable to build the core-lightning image, from both the custom instructions and also the using the docker file in the docker directory.
Tried on both `ubuntu amd64` and `mac arm64`.

**To Reproduce**
1. Attempt to build the core-lightning image
2. Image fails to build with the following error:

```
wiregen hsmd/hsmd_wiregen.h
cc ccan/ccan/cdump/tools/cdump-enumstr.c
cc ccan/ccan/cdump/cdump.c
Traceback (most recent call last):
  File "/opt/lightningd/tools/generate-wire.py", line 27, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [Makefile:337: hsmd/hsmd_wiregen.h] Error 1
make: *** Waiting for unfinished jobs....
The command '/bin/sh -c ./configure --prefix=/tmp/lightning_install --enable-static && make -j3 DEVELOPER=${DEVELOPER} && make install' returned a non-zero code: 2

```

**Expected behavior**
Image builds successfully.

**Screenshots**

**Desktop (please complete the following information):**
- OS: ubuntu 22 and m1 mac
- Polar Version: latest
- Docker Version: 20.10.18
- Docker Compose Version:  2.10.2

**Comment by niteshbalusu11** [comment]
Tried both v0.12.0 and v0.12.1 from their repo as the args of the docker file

**Comment by jamaljsr** [comment]
Hey @niteshbalusu11, I have not been able to get Core Lightning to build on arm64 either. I have to revisit this and see if I can get it working. I believe it requires a completely different Dockerfile.

The v0.12.0 amd64 image currently on Docker Hub was built using the Dockerfile currently in the repo. I'm not sure what's causing the issue you're running into but I'll try to run the build again myself later this week to see if I can reproduce it.

**Comment by niteshbalusu11** [comment]
Cool ok, thanks!

**Comment by jamaljsr** [comment]
See https://github.com/ElementsProject/lightning/issues/5655#issuecomment-1277379437 for the fix to this. You'll need to checkout the `docker-v0.12.1` branch.
