### ISSUE TITLE
Bug: Lost Blocks in Bitcoin-d after unclean node restart

### ISSUE THREAD

**Issue by G8XSU** [jamaljsr/polar#614]
**Describe the bug**
After a block is mined, bitcoin-core does not immediately save it to disk. 
But will broadcast it to clients. (in this case lightning nodes)

If bitcoin-node does not get cleanly stopped/restarted, that unpersisted block will be lost.
And when some client with previous block header tries to query it with blockhash, it will fail with "BlockNotFound"

**To Reproduce**
Mine a block then kill container or stop network.

**Solution**
* Polar must stop bitcoin d via rpc stop in shutdown script, so that it persists and flushes all data to disk before exiting. 
* It also needs to be handled in clients consuming bitcoin blocks.

**Comment by jamaljsr** [comment]
Thanks for the report and details. I have seen occasional issues with the LN nodes becoming out of sync with the bitcoind node but couldn't figure out why it was occurring. It's strange that bitcoind doesn't shutdown clean when it receives the `SIGTERM` signal from Docker. Do you have any isights into why this is the case?

The challenge is going to be how to handle shutting down via RPC before stopping the docker container and preventing it from automatically restarting. There could be a race between docker stopping the container while bitcoind is in the middle of restarting. I'll see if I can find a suitable solution. Likely will need to just turn off auto-restart for the bitcoind nodes only. For the LN nodes, Polar relies on them restarting while waiting for bitcoind to start.
