### ISSUE TITLE
Last 2 versions of LND not working

### ISSUE THREAD

**Issue by casey-bowman** [jamaljsr/polar#621]
Adding v0.15.2-beta LND nodes to a network works fine. 

However, when adding a node that's either v0.15.3-beta or v0.15.4-beta, the node is not able to start up. The following message appears - 

> Unable to connect to LND node 
> ENOENT: no such file or directory, 
> open '/home/username/.polar/networks/1/volumes/lnd/bob/tls.cert'

**To Reproduce**
Quit polar
Delete the folder ~/.polar
Start Polar
Update 
Create a network with only one bitcoin node
Click on background in order to view Network Designer
Select "Show All Versions"
Add a node using LND v0.15.2-beta
Start the network
Note that the node starts up correctly
Add a node using LND v0.15.3-beta
Note that this node _does not_ start up correctly
Add another node using LND v0.15.2-beta
Note that this node _does_ start up correctly
Add another node using LND v0.15.4-beta
Note that this node _does not_ start up correctly

**Expected behavior**
All nodes should start up correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/837800/200992159-8b2a80a3-9812-4466-a329-e365143daf24.png)

**Desktop:**
- OS: Pop!_OS 22.04 LTS 
- Polar Version: v1.4.0
- Docker Version: v20.10.21
- Docker Compose Version: v1.29.2

**Additional context**
Perhaps this is related to the issue I mentioned in a twitter DM to jamaljsr on Oct 6, when I tried to use a custom LND docker image. Maybe this is happening with the newest versions for the same reason. I didn't figure out the reason for that issue, since I realized I didn't need the custom image after all and then didn't spend any more time on the issue, but this reminds me of what I experienced then.

**Comment by jamaljsr** [comment]
Ah, I see what the issue was. I mistakenly pushed arm64 v8 images to docker hub and not x86. I pushed new images just now. You'll just need to delete your local `polarlightning/lnd` images in Docker then restart Polar. It will pull the updated images and they should work fine now.

**Comment by casey-bowman** [comment]
Great! Thanks, Jamal. I'll test them out today.

**Comment by casey-bowman** [comment]
They work now. Thank you

**Comment by benthecarman** [comment]
I am getting this issue on ubuntu amd64, the docker images don't update after I hit the update button it seems

**Comment by jamaljsr** [comment]
Did you delete the local docker images? Polar will not display that there are new node versions. You have to manually delete the images using the `docker` CLI then Polar will download the new images from Docker Hub when you start a new network.

**Comment by benthecarman** [comment]
That fixed!
