### ISSUE TITLE
Feature Request: vscode launch.json update with debug config

### ISSUE THREAD

**Issue by amovfx** [jamaljsr/polar#628]
**Is your feature request related to a problem? Please describe.**
vs code .launch file updated with a debug config

**Describe the solution you'd like**
Just a clear debug process

**Additional context**
I'm making decent progress, but I'm struggling to get a good debug workflow going with yarn dev

**Comment by jamaljsr** [comment]
This would be pretty cool. I currently use the Chrome DevTools debugger but it would be convenient to be able to debug right from VSCode. 👍

**Comment by amovfx** [comment]
I'm going to close this.
I found that working with jest is giving me this.
