### ISSUE TITLE
Bug: Viewing terminals on Linux just gives a loading animated icon

### ISSUE THREAD

**Issue by iangregsondev** [jamaljsr/polar#642]
**Describe the bug**
Attaching a screenshot, right click and click View Logs... Logs do not seem to display for LND or Bitcoin

![image](https://user-images.githubusercontent.com/2370364/210192079-a238474e-f60f-44e5-993b-109efc5ba09a.png)

**To Reproduce**
1.Rigjht click a node i.e lnd or bitcoin
2. Click on View Logs
3. Window opens but it just sits there as if it is loading

**Expected behavior**

Screens should show the log information.

**Desktop (please complete the following information):**
- OS: Zorin 16.2 (Zorin is almost identical to Ubuntu, its based upon it)
- Polar Version: 1.4.0

**Comment by iangregsondev** [comment]
Oh and I forgot to mention, I checked the log files on disk, and I don't see any specific issue being output.

**Comment by jamaljsr** [comment]
Thanks for the bug report. I haven't had a chance to dive into all of the new Docker Desktop issues on Linux as I've been working to get Taro support added. This stuff is next on my todo list.

**Comment by Abdulkbk** [comment]
Hi @jamaljsr, I'd like to work on this issue

**Comment by jamaljsr** [comment]
Hey @Abdulkbk this issue is actually resolved in #879. I'll close this.

**Comment by Abdulkbk** [comment]
> Hey @Abdulkbk this issue is actually resolved in #879. I'll close this.

Alright thanks. I'll look for another one
