### ISSUE TITLE
Polar cannot be opened because the developer cannot be verified on macOS

### ISSUE THREAD

**Issue by Indiecake** [jamaljsr/polar#650]
**Describe the bug**
When Ii was trying to get polar running on my mac I was unable to open the app because the OS show me an alert instead & ask me to delete Polar.

**To Reproduce**
1. Go to 'Polar release v1.4.0'
2. Download polar-mac-x64-v1.4.0.dmg file
3. Install Polar
4. Open Polar & See the error

**Expected behavior**
Open polar app on macOS

**Screenshots**
![Screen Shot 2023-01-06 at 10 14 04 a m](https://user-images.githubusercontent.com/24942564/211064873-6c8649c4-bafb-439c-8231-8430f1a3d7dd.png)

**Desktop (please complete the following information):**
- OS: [OSX Monterey v12.4]
- Polar Version: [1.4.0]
- Docker Version: [20.10.17]
- Docker Compose Version: [1.29.2]

**Comment by amovfx** [comment]
This is something you have to adjust in your security settings.
![Screenshot 2023-01-07 at 11 23 01 AM](https://user-images.githubusercontent.com/45839100/211165126-ba7107df-4ceb-4a0a-b6c0-d908511ef8d8.png)

**Comment by jamaljsr** [comment]
Another workaround is to open your Applications folder in Finder, then right-click on Polar.app then click Open. You'll see the warning below which allows you to continue to open Polar. After doing this once, you can continue to open it without ever seeing the "Polar cannot be opened ..." message again. It will only show up again if you download and install a new version.

![image](https://user-images.githubusercontent.com/1356600/211392666-9b3f4f32-9b96-47b0-b621-0ae3049afe12.png)

See https://github.com/jamaljsr/polar/issues/549#issuecomment-1100321836 for some context on why I choose not to create a developer certificate.
