### ISSUE TITLE
Tutorial Requirements

### ISSUE THREAD

**Issue by fyt136** [jamaljsr/polar#665]
Does polar have a tutorial suitable for beginners？

**Comment by jamaljsr** [comment]
I've tried to make Polar very intuitive so you should be able to figure most things out by just clicking around. There isn't many guides out there on how to use Polar specifically, but here are a couple links that you may find helpful.

A guide to building an app using Polar and the LND APIs.
https://docs.lightning.engineering/lapps/guides/polar-lapps

A PlebDevs stream where Polar is used to build an app
https://twitch.tv/videos/1720437473

A demo I did a while back during a presentation on Polar
https://youtu.be/XvEjZs3fifk?t=1223
