### ISSUE TITLE
Feature Request: Minimize to system tray

### ISSUE THREAD

**Issue by benthecarman** [jamaljsr/polar#693]
Would be nice to minimize to system tray. A lot of the time I am not actively using the various functions of polar but just want the network running so my application can call upon it.

**Comment by jamaljsr** [comment]
Good idea. Which OS are you running on? I suppose we should support this on all of them, but just curious.

**Comment by benthecarman** [comment]
Ubuntu

**Comment by AdamuAbba** [comment]
hey @jamaljsr I'd love to work on this.

**Comment by jamaljsr** [comment]
ok, sounds good. thanks! 👍
