### ISSUE TITLE
Feature Request: Support Certificate Generation with tlsextraip

### ISSUE THREAD

**Issue by icebaker** [jamaljsr/polar#697]
**Is your feature request related to a problem? Please describe.**

I'm facing issues when trying to access Polar LND nodes' GRPC API via Docker containers:

```text
14:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.17.0.1:10001: Peer name 172.17.0.1 is not in peer certificate. debug_error_string:{UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.17.0.1:10001: Peer name 172.17.0.1 is not in peer certificate {grpc_status:14, created_time:"2023-03-26T19:05:44.01258756+00:00"}}
```

The reason for this is that the request inside the Docker container comes from the Docker Host IP (`172.17.0.1`), which is not an IP allowed in the certificate.

I tried to modify the _Docker Startup Command_ with `tlsextraip=172.17.0.1`, but it has no effect, as the certificate needs to be regenerated to include the IP. I tried to launch the terminal, delete the `tls.cert` and `tls.key`, and restart the node (which works on LND; you set the `tlsextraip`, delete the files, and it will be generated again with the IP added to the certificate once restarted). But it doesn't work; the node doesn't come online anymore, and the new certificates aren't generated.

**Describe the solution you'd like**
I would like to add `tlsextraip=172.17.0.1` and have the certificates generated with the new allowed IP, or find another straightforward solution for this.

**Additional context**
In the context of development and testing, it's helpful to work with multiple Docker containers and networks, or set up infrastructure to run tests and easily allow specific IPs. Alternatively, allowing any IP (0.0.0.0) by default would be very helpful as well. This is a common need in my projects: [_Docker and Remote Access_](https://icebaker.github.io/lighstorm/#/README?id=docker-and-remote-access)

**Comment by jamaljsr** [comment]
Thanks for the detailed report. This is a known issue (#508) and the current workaround is to delete the certs, stop the LND node, restart Polar, start the LND node. It should work fine then.

A more permanent fix is in #698
