### ISSUE TITLE
Bug: Source and destination of unconfirmed channel is shown reverse

### ISSUE THREAD

**Issue by TKone7** [jamaljsr/polar#699]
**Describe the bug**
When I open a channel (through cli) between two lnd nodes the channel details (sidebar) show source and destination in reverse. Only after the channel open transaction is mined, the source and destination are correct.

**To Reproduce**
1. Launch terminal for `alice`
2. Run `lncli openchannel <bob-pubkey> 100000`
3. Check channel details
4. Source will be `bob` and destination `alice`
6. Mine 6 blocks
7. Source and destination will be the reverse

**Expected behavior**
Source should be `alice` and destination `bob`

**Desktop (please complete the following information):**
- OS: Arch Linux
- Polar v1.4.0
- Docker v23.0.1
- Compose v2.16.0

**Additional context**
- only between two lnd nodes (v0.15.1-beta)
- only while funding tx is unconfirmed

**Comment by amovfx** [comment]
Hey @TKone7,
thanks for reporting this, Ill give it a look when I get a moment.

**Comment by amovfx** [comment]
I have this bug confirmed. Ill take a look.

**Comment by amovfx** [comment]
Just put in a PR for this.
