### ISSUE TITLE
Lightning terminal: Litd

### ISSUE THREAD

**Issue by eNzyOfficial** [jamaljsr/polar#706]
Apologies to post this as a github issue, I wasn't able to find a slack or discord to jump into and ask.

I was looking to see if it's possible to setup and use litd but not having much luck.

Is this feature available or would there a way to get it up and running in one of the LND nodes through the terminal fairly easily?

Thanks!

**Comment by jamaljsr** [comment]
While this isn't a supported use case for `litd`, you can get it partially working using the regtest loopserver and testnet pool server. You won't be able to use Pool properly, but you can use Loop and LNC. 

See https://github.com/lightninglabs/lightning-terminal/issues/359#issuecomment-1208279772
