### ISSUE TITLE
Bug: Cannot send multipart payment from a LND node ("no route found")

### ISSUE THREAD

**Issue by raweber42** [jamaljsr/polar#741]
**Describe the bug**
When I try to make a multipart payment (payment through multiple channels) this doesn't work when done with an LND node. It works with Core Lightning though.

**To Reproduce**
1. Create a new network
2. Add 3 LND nodes
3. open channel between the three of them to make a circle (Alice->Bob, Alice->Carol, Bob->Carol) with 100.000sats capacity each.
4. Create an invoice from Carol for 150.000sats to force a MPP
5. Let Alice try to pay
6. Examine the 'no route found' error

**Expected behavior**
Payment should go through.

**Desktop (please complete the following information):**
- OS: MacOS
- Polar Version: 1.4.0
- Docker Version: 20.10.23
- Docker Compose Version: 2.15.1

**Additional context**

**Comment by jamaljsr** [comment]
Yes, this is correct. The Pay Invoice feature in Polar currently uses the old `SendPayment` RPC which doesn't support MPP. We'd need to update to the `SendPaymentV2` RPC. As a workaround, you can use the Terminal in Polar to run `lncli payinvoice <payreq>` to pay the MPP invoice.

**Comment by raweber42** [comment]
Okay, thanks for the update!

**Comment by jamaljsr** [comment]
Going to close this since there is a suitable workaround.
