### ISSUE TITLE
Bug: Can't create network - (root) additional property name not allowed

### ISSUE THREAD

**Issue by madtoshi** [jamaljsr/polar#771]
Hi, just started using Polar but can't get up and running. Receiving "(root) Additional property name is not allowed" error when attempting to start/restart network. Any help would be appreciated. Thanks

Running Polar v2.0.0, Docker v20.10.12, and Compose v2.2.3 on macOS Catalina 10.15.7

**Comment by jamaljsr** [comment]
This is a new error I haven't seen before. I'm not sure where this is coming from. Can you share your logs which are stored in `~/.polar/logs/`?

**Comment by CRex15** [comment]
I got this error as well and was on Compose v2.2.3. I had to update my docker compose. Moving to 2.20.3 solved it.

**Comment by jamaljsr** [comment]
Thanks for posting the fix @CRex15. I hadn't noticed that the compose version was out of date there.

**Comment by vindard** [comment]
I got caught by this too. Just [bumped my version](https://github.com/vindard/my-linux-setup/commit/af92a885a93e7b7d887cb020f4edb38e2958b78d) from v2.0.1 to v2.23.3 😅
