### ISSUE TITLE
Bug: When I open channel on LND Node, the UI feedback me: "Cannot convert undefined or null to object". 

### ISSUE THREAD

**Issue by UXUY-Labs** [jamaljsr/polar#802]
**Describe the bug**
When I open channel on LND Node, the UI feedback me: "Cannot convert undefined or null to object". 

**To Reproduce**
1. Open Polar
2. Create Network
3. Add two LND Node, and deposite default value into
4. Open channel each other

**Expected behavior**

**Screenshots**
<img width="1493" alt="Screenshot 2023-11-09 at 10 10 11 AM" src="https://github.com/jamaljsr/polar/assets/139519862/4de3ce40-3af9-4e8d-a017-0f22608a306e">

**Desktop (please complete the following information):**
- OS: macOS Sonoma 14.0
- Polar Version: v2.1.0
- Docker Version: v24.0.6
- Docker Compose Version: v2.23.0-desktop.1

**Comment by jamaljsr** [comment]
I don't see this issue on my end. 
- What versions of LND are you using? 
- Are you using any custom startup command flags?
- Can you share the logs stored in `~/.polar/logs`?
