### ISSUE TITLE
Bug: Eclair - Error in GUI when open channel

### ISSUE THREAD

**Issue by kulisekf** [jamaljsr/polar#804]
**Describe the bug**
When I open a channel within 2 Eclair nodes I get the error Unable to get node information from xxx (eg Alice, Bob) in GUI - in the terminal I can see the channel and can work with it, but in the GUI I can't see it and the GUI subsequently not working properly

**To Reproduce**
1. Create new network -> 2 Eclair v0.9.0 + 2 Bitcoin Core v25.0
2. Start network
3. Deposit funds (at Alice) - At node go to "Actions" and click on "Deposit" for 1,000,000 sats
4. Open channel to Bob (either via "Actions" -> "Open Channel" - "Ourgoing", or drag "from dot to dot" within the graphic display of the network). There is no need to change anything in the settings for opening a new node
5. Then I see:
![image](https://github.com/jamaljsr/polar/assets/120821113/80fc2153-ac54-4d5b-b1e1-b63158492a69)
  subsequently in the node view (on each of them) I see error:
![image](https://github.com/jamaljsr/polar/assets/120821113/8b0bb5a7-8154-4332-bbd9-171dc77e193d)
   but in terminal channel exist:
`eclair@alice:/app$ eclair-cli allchannels`
[
  {
    "shortChannelId": "108x1x1",
    "a": "03210acf8ff1d593478ffc948fa3461e219824972ca3878949486fc3a990c27b0a",
    "b": "03c302b2f55a4385dbdf8157baff4f25b471b7f1e5566df714e9438e5e2ed6bfd0"
  }
]

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Home; version 10.0.19045 N/A Build 19045
- Polar Version: v2.1.0
- Docker Version: v20.10.21
- Docker Compose Version: v2.13.0

**Comment by jamaljsr** [comment]
Thanks for the bug report. I'll look into this.
