### ISSUE TITLE
access to bitcoin.config file? "Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate)"

### ISSUE THREAD

**Issue by hdlslm** [jamaljsr/polar#825]
is it possible to get access to  and/or modify the bitcoin.config file in polar? i'm tinkering around with utxo's in the terminal and i'm getting "Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate)" error message when sending a tx. thanks!!

**Comment by uwla** [comment]
Maybe modify the file `~/.polar/networks/1/docker-compose.yml`. There you will find a `-fallbackfee=0.0002` default flag for bitcoin-core nodes and a `on-chain-fees.feerate-tolerance.ratio-high=10000.0` flag for eclair LN nodes. You can modify the flags passed to the containers there.

**Comment by hdlslm** [comment]
ok thanks. i'll try modifying the -fallbackfee flag to see if that works.

**Comment by hdlslm** [comment]
i ended up successfully sending the rawutxo with the 2nd optional argument set to 0 to accept any fee rate per the btc api reference.
