### ISSUE TITLE
Feature Request: add a description field for each network

### ISSUE THREAD

**Issue by orbitalturtle** [jamaljsr/polar#836]
**Is your feature request related to a problem? Please describe.**

I've been using Polar a lot (it's the best!). I'm starting to have quite a lot of different networks and I often have trouble differentiating between them. It'd also be nice to be able to save some notes reminding me of what I was trying to accomplish.

**Describe the solution you'd like**
Each network has a `name` field. But it might be nice to have a multi-line `description` field alongside for adding notes.

Figured I'd post an issue and see if anyone else would find this useful.

**Comment by jamaljsr** [comment]
Hey @orbitalturtle, thanks for the feedback. This sounds like a good idea to me.

**Comment by Nonnyjoe** [comment]
Hi @jamaljsr ... I'll like to handle this
