### ISSUE TITLE
Feature Request: Migrate from `c-lightning-REST` to core lightning's build in plugin `clnrest`

### ISSUE THREAD

**Issue by ShahanaFarooqui** [jamaljsr/polar#975]
Please migrate Polar from `c-lightning-REST` to core lightning's built-in plugin `clnrest` as:
- `c-lightning-REST` will soon start it's sunset.
- Users are getting confused between c-lightning-REST and clnrest. They are trying to troubleshoot by clnrest documentation rather than c-lightning-REST.

**Comment by jamaljsr** [comment]
Hi @ShahanaFarooqui I have already made the switch to `clnrest` in #879. This update is included in the latest v3.0.0 release. 

Are users facing this confusion using the latest Polar version?

**Comment by ShahanaFarooqui** [comment]
Sorry, I am not receiving any messages from GitHub, including the tagged ones. I am not sure about the version they are using. I will ask them to update the version and open another issue if needed. Thank you for looking into it, closing this issue.
