### ISSUE TITLE
Bug: GUI does not take the decimal point into account when showing the Taproot Assets balance

### ISSUE THREAD

**Issue by yo-mr-white** [jamaljsr/polar#986]
If I mint a new Taproot Asset from the command line and use a decimal point:

`tapcli assets mint --type normal --name beefbux --supply 1000000 --decimal_display 3 --meta_bytes '{"hello":true}' --meta_type json --new_grouped_asset`

In the GUI, this fact is not taken into account, and instead of displaying 1000.000, it shows 1000000.

See the details in the help section:

`--decimal_display value  the number of decimal places, asset amounts, are shift to the left converting asset integer amountsinto UI-recognizable fractional quantity (e.g. an asset with amount100 and decimal display of 2 is displayed as 1.00 in the wallet) (default: 0)`

It’s a minor issue, so just FYI.

**Comment by jamaljsr** [comment]
Thanks for the bug report. You are correct, Polar should display the amount based on the `decimal_display` value.

**Comment by jamaljsr** [comment]
This is resolved in #1040.
